/*
 * This file is generated by jOOQ.
 */
package com.opac.scms.tables;


import com.opac.scms.Applet;
import com.opac.scms.tables.records.AgentsRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Agents extends TableImpl<AgentsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>applet.agents</code>
     */
    public static final Agents AGENTS = new Agents();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AgentsRecord> getRecordType() {
        return AgentsRecord.class;
    }

    /**
     * The column <code>applet.agents.id</code>.
     */
    public final TableField<AgentsRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>applet.agents.p_status</code>.
     */
    public final TableField<AgentsRecord, Integer> P_STATUS = createField(DSL.name("p_status"), SQLDataType.INTEGER.defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>applet.agents.p_mechanism</code>.
     */
    public final TableField<AgentsRecord, String> P_MECHANISM = createField(DSL.name("p_mechanism"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.p_conf_level</code>.
     */
    public final TableField<AgentsRecord, Integer> P_CONF_LEVEL = createField(DSL.name("p_conf_level"), SQLDataType.INTEGER.defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>applet.agents.p_agency_id</code>.
     */
    public final TableField<AgentsRecord, String> P_AGENCY_ID = createField(DSL.name("p_agency_id"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.p_agency_npn</code>.
     */
    public final TableField<AgentsRecord, String> P_AGENCY_NPN = createField(DSL.name("p_agency_npn"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.p_agency_info</code>.
     */
    public final TableField<AgentsRecord, String> P_AGENCY_INFO = createField(DSL.name("p_agency_info"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.p_logs</code>.
     */
    public final TableField<AgentsRecord, String> P_LOGS = createField(DSL.name("p_logs"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.npn</code>.
     */
    public final TableField<AgentsRecord, String> NPN = createField(DSL.name("npn"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.fullname</code>.
     */
    public final TableField<AgentsRecord, String> FULLNAME = createField(DSL.name("fullname"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.firstname</code>.
     */
    public final TableField<AgentsRecord, String> FIRSTNAME = createField(DSL.name("firstname"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.middlename</code>.
     */
    public final TableField<AgentsRecord, String> MIDDLENAME = createField(DSL.name("middlename"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.lastname</code>.
     */
    public final TableField<AgentsRecord, String> LASTNAME = createField(DSL.name("lastname"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.suffix</code>.
     */
    public final TableField<AgentsRecord, String> SUFFIX = createField(DSL.name("suffix"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.primary_addressid</code>.
     */
    public final TableField<AgentsRecord, String> PRIMARY_ADDRESSID = createField(DSL.name("primary_addressid"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.primary_address1</code>.
     */
    public final TableField<AgentsRecord, String> PRIMARY_ADDRESS1 = createField(DSL.name("primary_address1"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.primary_address2</code>.
     */
    public final TableField<AgentsRecord, String> PRIMARY_ADDRESS2 = createField(DSL.name("primary_address2"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.primary_city</code>.
     */
    public final TableField<AgentsRecord, String> PRIMARY_CITY = createField(DSL.name("primary_city"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.primary_state</code>.
     */
    public final TableField<AgentsRecord, String> PRIMARY_STATE = createField(DSL.name("primary_state"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.primary_zipcode</code>.
     */
    public final TableField<AgentsRecord, String> PRIMARY_ZIPCODE = createField(DSL.name("primary_zipcode"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.primary_zipcode4</code>.
     */
    public final TableField<AgentsRecord, String> PRIMARY_ZIPCODE4 = createField(DSL.name("primary_zipcode4"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.primary_metropolitanarea</code>.
     */
    public final TableField<AgentsRecord, String> PRIMARY_METROPOLITANAREA = createField(DSL.name("primary_metropolitanarea"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.primary_county</code>.
     */
    public final TableField<AgentsRecord, String> PRIMARY_COUNTY = createField(DSL.name("primary_county"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.primary_longitude</code>.
     */
    public final TableField<AgentsRecord, BigDecimal> PRIMARY_LONGITUDE = createField(DSL.name("primary_longitude"), SQLDataType.DECIMAL(20, 17), this, "");

    /**
     * The column <code>applet.agents.primary_latitude</code>.
     */
    public final TableField<AgentsRecord, BigDecimal> PRIMARY_LATITUDE = createField(DSL.name("primary_latitude"), SQLDataType.DECIMAL(20, 17), this, "");

    /**
     * The column <code>applet.agents.primary_phone</code>.
     */
    public final TableField<AgentsRecord, String> PRIMARY_PHONE = createField(DSL.name("primary_phone"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.home_addressid</code>.
     */
    public final TableField<AgentsRecord, String> HOME_ADDRESSID = createField(DSL.name("home_addressid"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.home_address1</code>.
     */
    public final TableField<AgentsRecord, String> HOME_ADDRESS1 = createField(DSL.name("home_address1"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.home_address2</code>.
     */
    public final TableField<AgentsRecord, String> HOME_ADDRESS2 = createField(DSL.name("home_address2"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.home_city</code>.
     */
    public final TableField<AgentsRecord, String> HOME_CITY = createField(DSL.name("home_city"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.home_state</code>.
     */
    public final TableField<AgentsRecord, String> HOME_STATE = createField(DSL.name("home_state"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.home_zipcode</code>.
     */
    public final TableField<AgentsRecord, String> HOME_ZIPCODE = createField(DSL.name("home_zipcode"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.home_zipcode4</code>.
     */
    public final TableField<AgentsRecord, String> HOME_ZIPCODE4 = createField(DSL.name("home_zipcode4"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.home_metropolitanarea</code>.
     */
    public final TableField<AgentsRecord, String> HOME_METROPOLITANAREA = createField(DSL.name("home_metropolitanarea"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.home_county</code>.
     */
    public final TableField<AgentsRecord, String> HOME_COUNTY = createField(DSL.name("home_county"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.home_longitude</code>.
     */
    public final TableField<AgentsRecord, BigDecimal> HOME_LONGITUDE = createField(DSL.name("home_longitude"), SQLDataType.DECIMAL(20, 17), this, "");

    /**
     * The column <code>applet.agents.home_latitude</code>.
     */
    public final TableField<AgentsRecord, BigDecimal> HOME_LATITUDE = createField(DSL.name("home_latitude"), SQLDataType.DECIMAL(20, 17), this, "");

    /**
     * The column <code>applet.agents.home_phone</code>.
     */
    public final TableField<AgentsRecord, String> HOME_PHONE = createField(DSL.name("home_phone"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.email_businesstype</code>.
     */
    public final TableField<AgentsRecord, String> EMAIL_BUSINESSTYPE = createField(DSL.name("email_businesstype"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.email_business2type</code>.
     */
    public final TableField<AgentsRecord, String> EMAIL_BUSINESS2TYPE = createField(DSL.name("email_business2type"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.email_personaltype</code>.
     */
    public final TableField<AgentsRecord, String> EMAIL_PERSONALTYPE = createField(DSL.name("email_personaltype"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.dbaname</code>.
     */
    public final TableField<AgentsRecord, String> DBANAME = createField(DSL.name("dbaname"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.number_yearsanagent</code>.
     */
    public final TableField<AgentsRecord, String> NUMBER_YEARSANAGENT = createField(DSL.name("number_yearsanagent"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.repcrd</code>.
     */
    public final TableField<AgentsRecord, String> REPCRD = createField(DSL.name("repcrd"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.securitiesregisteredagent</code>.
     */
    public final TableField<AgentsRecord, String> SECURITIESREGISTEREDAGENT = createField(DSL.name("securitiesregisteredagent"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.brokerdealeraffiliation</code>.
     */
    public final TableField<AgentsRecord, String> BROKERDEALERAFFILIATION = createField(DSL.name("brokerdealeraffiliation"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.sellsretirementplanproducts</code>.
     */
    public final TableField<AgentsRecord, String> SELLSRETIREMENTPLANPRODUCTS = createField(DSL.name("sellsretirementplanproducts"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.earliestappointmentdate</code>.
     */
    public final TableField<AgentsRecord, String> EARLIESTAPPOINTMENTDATE = createField(DSL.name("earliestappointmentdate"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.carrierappointments</code>.
     */
    public final TableField<AgentsRecord, String> CARRIERAPPOINTMENTS = createField(DSL.name("carrierappointments"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.dateofbirth_year</code>.
     */
    public final TableField<AgentsRecord, String> DATEOFBIRTH_YEAR = createField(DSL.name("dateofbirth_year"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.dateofbirth_full</code>.
     */
    public final TableField<AgentsRecord, String> DATEOFBIRTH_FULL = createField(DSL.name("dateofbirth_full"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.gender</code>.
     */
    public final TableField<AgentsRecord, String> GENDER = createField(DSL.name("gender"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.agentlicensetype_health</code>.
     */
    public final TableField<AgentsRecord, String> AGENTLICENSETYPE_HEALTH = createField(DSL.name("agentlicensetype_health"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.number_statelicenses_health</code>.
     */
    public final TableField<AgentsRecord, String> NUMBER_STATELICENSES_HEALTH = createField(DSL.name("number_statelicenses_health"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.agentlicensetype_life</code>.
     */
    public final TableField<AgentsRecord, String> AGENTLICENSETYPE_LIFE = createField(DSL.name("agentlicensetype_life"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.number_statelicenses_life</code>.
     */
    public final TableField<AgentsRecord, String> NUMBER_STATELICENSES_LIFE = createField(DSL.name("number_statelicenses_life"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.agentlicensetype_propertycasualty</code>.
     */
    public final TableField<AgentsRecord, String> AGENTLICENSETYPE_PROPERTYCASUALTY = createField(DSL.name("agentlicensetype_propertycasualty"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.number_statelicenses_propertycasualty</code>.
     */
    public final TableField<AgentsRecord, String> NUMBER_STATELICENSES_PROPERTYCASUALTY = createField(DSL.name("number_statelicenses_propertycasualty"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.agentlicensetype_variableproducts</code>.
     */
    public final TableField<AgentsRecord, String> AGENTLICENSETYPE_VARIABLEPRODUCTS = createField(DSL.name("agentlicensetype_variableproducts"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.number_statelicenses_variableproducts</code>.
     */
    public final TableField<AgentsRecord, String> NUMBER_STATELICENSES_VARIABLEPRODUCTS = createField(DSL.name("number_statelicenses_variableproducts"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.dateaddedtodiscoverydatabase</code>.
     */
    public final TableField<AgentsRecord, String> DATEADDEDTODISCOVERYDATABASE = createField(DSL.name("dateaddedtodiscoverydatabase"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.home_3digitsectionalzip</code>.
     */
    public final TableField<AgentsRecord, String> HOME_3DIGITSECTIONALZIP = createField(DSL.name("home_3digitsectionalzip"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.primary_3digitsectionalzip</code>.
     */
    public final TableField<AgentsRecord, String> PRIMARY_3DIGITSECTIONALZIP = createField(DSL.name("primary_3digitsectionalzip"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.uspscertified_homeaddress</code>.
     */
    public final TableField<AgentsRecord, String> USPSCERTIFIED_HOMEADDRESS = createField(DSL.name("uspscertified_homeaddress"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.uspscertified_primaryaddress</code>.
     */
    public final TableField<AgentsRecord, String> USPSCERTIFIED_PRIMARYADDRESS = createField(DSL.name("uspscertified_primaryaddress"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.primary_addresstype</code>.
     */
    public final TableField<AgentsRecord, String> PRIMARY_ADDRESSTYPE = createField(DSL.name("primary_addresstype"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.primary_addressupdate</code>.
     */
    public final TableField<AgentsRecord, String> PRIMARY_ADDRESSUPDATE = createField(DSL.name("primary_addressupdate"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.primary_phonetype</code>.
     */
    public final TableField<AgentsRecord, String> PRIMARY_PHONETYPE = createField(DSL.name("primary_phonetype"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.primary_phoneupdate</code>.
     */
    public final TableField<AgentsRecord, String> PRIMARY_PHONEUPDATE = createField(DSL.name("primary_phoneupdate"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.home_addressupdate</code>.
     */
    public final TableField<AgentsRecord, String> HOME_ADDRESSUPDATE = createField(DSL.name("home_addressupdate"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.discoverycontactid</code>.
     */
    public final TableField<AgentsRecord, String> DISCOVERYCONTACTID = createField(DSL.name("discoverycontactid"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.website</code>.
     */
    public final TableField<AgentsRecord, String> WEBSITE = createField(DSL.name("website"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.firmname</code>.
     */
    public final TableField<AgentsRecord, String> FIRMNAME = createField(DSL.name("firmname"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.riaaffiliation</code>.
     */
    public final TableField<AgentsRecord, String> RIAAFFILIATION = createField(DSL.name("riaaffiliation"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.primary_geolocationurl</code>.
     */
    public final TableField<AgentsRecord, String> PRIMARY_GEOLOCATIONURL = createField(DSL.name("primary_geolocationurl"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.home_geolocationurl</code>.
     */
    public final TableField<AgentsRecord, String> HOME_GEOLOCATIONURL = createField(DSL.name("home_geolocationurl"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.becameagentdate</code>.
     */
    public final TableField<AgentsRecord, String> BECAMEAGENTDATE = createField(DSL.name("becameagentdate"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.discoverydataprofileurl</code>.
     */
    public final TableField<AgentsRecord, String> DISCOVERYDATAPROFILEURL = createField(DSL.name("discoverydataprofileurl"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.primary_streetaddress</code>.
     */
    public final TableField<AgentsRecord, String> PRIMARY_STREETADDRESS = createField(DSL.name("primary_streetaddress"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.home_streetaddress</code>.
     */
    public final TableField<AgentsRecord, String> HOME_STREETADDRESS = createField(DSL.name("home_streetaddress"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.primary_country</code>.
     */
    public final TableField<AgentsRecord, String> PRIMARY_COUNTRY = createField(DSL.name("primary_country"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.home_country</code>.
     */
    public final TableField<AgentsRecord, String> HOME_COUNTRY = createField(DSL.name("home_country"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.othernames</code>.
     */
    public final TableField<AgentsRecord, String> OTHERNAMES = createField(DSL.name("othernames"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.preferredname</code>.
     */
    public final TableField<AgentsRecord, String> PREFERREDNAME = createField(DSL.name("preferredname"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.dateofbirth_mm_dd</code>.
     */
    public final TableField<AgentsRecord, String> DATEOFBIRTH_MM_DD = createField(DSL.name("dateofbirth_mm_dd"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.personalwebsite</code>.
     */
    public final TableField<AgentsRecord, String> PERSONALWEBSITE = createField(DSL.name("personalwebsite"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.agents.created_at</code>.
     */
    public final TableField<AgentsRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column <code>applet.agents.updated_at</code>.
     */
    public final TableField<AgentsRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(0), this, "");

    private Agents(Name alias, Table<AgentsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Agents(Name alias, Table<AgentsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>applet.agents</code> table reference
     */
    public Agents(String alias) {
        this(DSL.name(alias), AGENTS);
    }

    /**
     * Create an aliased <code>applet.agents</code> table reference
     */
    public Agents(Name alias) {
        this(alias, AGENTS);
    }

    /**
     * Create a <code>applet.agents</code> table reference
     */
    public Agents() {
        this(DSL.name("agents"), null);
    }

    public <O extends Record> Agents(Table<O> child, ForeignKey<O, AgentsRecord> key) {
        super(child, key, AGENTS);
    }

    @Override
    public Schema getSchema() {
        return Applet.APPLET;
    }

    @Override
    public Agents as(String alias) {
        return new Agents(DSL.name(alias), this);
    }

    @Override
    public Agents as(Name alias) {
        return new Agents(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Agents rename(String name) {
        return new Agents(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Agents rename(Name name) {
        return new Agents(name, null);
    }
}
