/*
 * This file is generated by jOOQ.
 */
package com.opac.scms.tables;


import com.opac.scms.Applet;
import com.opac.scms.Keys;
import com.opac.scms.tables.records.NotificationsRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row8;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Notifications extends TableImpl<NotificationsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>applet.notifications</code>
     */
    public static final Notifications NOTIFICATIONS = new Notifications();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<NotificationsRecord> getRecordType() {
        return NotificationsRecord.class;
    }

    /**
     * The column <code>applet.notifications.id</code>.
     */
    public final TableField<NotificationsRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>applet.notifications.advert_id</code>.
     */
    public final TableField<NotificationsRecord, Integer> ADVERT_ID = createField(DSL.name("advert_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>applet.notifications.chat_id</code>.
     */
    public final TableField<NotificationsRecord, Integer> CHAT_ID = createField(DSL.name("chat_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>applet.notifications.user_id</code>. usuario q provoca la notificacion
     */
    public final TableField<NotificationsRecord, Integer> USER_ID = createField(DSL.name("user_id"), SQLDataType.INTEGER.nullable(false), this, "usuario q provoca la notificacion");

    /**
     * The column <code>applet.notifications.type</code>.
     */
    public final TableField<NotificationsRecord, Byte> TYPE = createField(DSL.name("type"), SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>applet.notifications.message</code>.
     */
    public final TableField<NotificationsRecord, String> MESSAGE = createField(DSL.name("message"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>applet.notifications.created</code>.
     */
    public final TableField<NotificationsRecord, LocalDateTime> CREATED = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column <code>applet.notifications.modified</code>.
     */
    public final TableField<NotificationsRecord, LocalDateTime> MODIFIED = createField(DSL.name("modified"), SQLDataType.LOCALDATETIME(0), this, "");

    private Notifications(Name alias, Table<NotificationsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Notifications(Name alias, Table<NotificationsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>applet.notifications</code> table reference
     */
    public Notifications(String alias) {
        this(DSL.name(alias), NOTIFICATIONS);
    }

    /**
     * Create an aliased <code>applet.notifications</code> table reference
     */
    public Notifications(Name alias) {
        this(alias, NOTIFICATIONS);
    }

    /**
     * Create a <code>applet.notifications</code> table reference
     */
    public Notifications() {
        this(DSL.name("notifications"), null);
    }

    public <O extends Record> Notifications(Table<O> child, ForeignKey<O, NotificationsRecord> key) {
        super(child, key, NOTIFICATIONS);
    }

    @Override
    public Schema getSchema() {
        return Applet.APPLET;
    }

    @Override
    public Identity<NotificationsRecord, Integer> getIdentity() {
        return (Identity<NotificationsRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<NotificationsRecord> getPrimaryKey() {
        return Keys.KEY_NOTIFICATIONS_PRIMARY;
    }

    @Override
    public List<UniqueKey<NotificationsRecord>> getKeys() {
        return Arrays.<UniqueKey<NotificationsRecord>>asList(Keys.KEY_NOTIFICATIONS_PRIMARY);
    }

    @Override
    public Notifications as(String alias) {
        return new Notifications(DSL.name(alias), this);
    }

    @Override
    public Notifications as(Name alias) {
        return new Notifications(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Notifications rename(String name) {
        return new Notifications(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Notifications rename(Name name) {
        return new Notifications(name, null);
    }

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, Integer, Integer, Integer, Byte, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }
}
