/*
 * This file is generated by jOOQ.
 */
package com.opac.scms.tables;


import com.opac.scms.Applet;
import com.opac.scms.tables.records.UsersCopyRecord;

import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersCopy extends TableImpl<UsersCopyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>applet.users_copy</code>
     */
    public static final UsersCopy USERS_COPY = new UsersCopy();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UsersCopyRecord> getRecordType() {
        return UsersCopyRecord.class;
    }

    /**
     * The column <code>applet.users_copy.id</code>.
     */
    public final TableField<UsersCopyRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>applet.users_copy.name</code>.
     */
    public final TableField<UsersCopyRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>applet.users_copy.phone</code>.
     */
    public final TableField<UsersCopyRecord, String> PHONE = createField(DSL.name("phone"), SQLDataType.VARCHAR(35), this, "");

    /**
     * The column <code>applet.users_copy.last_name</code>.
     */
    public final TableField<UsersCopyRecord, String> LAST_NAME = createField(DSL.name("last_name"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>applet.users_copy.email</code>.
     */
    public final TableField<UsersCopyRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>applet.users_copy.username</code>.
     */
    public final TableField<UsersCopyRecord, String> USERNAME = createField(DSL.name("username"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>applet.users_copy.password</code>.
     */
    public final TableField<UsersCopyRecord, String> PASSWORD = createField(DSL.name("password"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.users_copy.active</code>.
     */
    public final TableField<UsersCopyRecord, Byte> ACTIVE = createField(DSL.name("active"), SQLDataType.TINYINT.nullable(false).defaultValue(DSL.inline("1", SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>applet.users_copy.facebook_id</code>.
     */
    public final TableField<UsersCopyRecord, String> FACEBOOK_ID = createField(DSL.name("facebook_id"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.users_copy.google_id</code>.
     */
    public final TableField<UsersCopyRecord, String> GOOGLE_ID = createField(DSL.name("google_id"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.users_copy.twitter_id</code>.
     */
    public final TableField<UsersCopyRecord, String> TWITTER_ID = createField(DSL.name("twitter_id"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.users_copy.last_connection</code>.
     */
    public final TableField<UsersCopyRecord, LocalDateTime> LAST_CONNECTION = createField(DSL.name("last_connection"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column <code>applet.users_copy.mangopay_id</code>.
     */
    public final TableField<UsersCopyRecord, String> MANGOPAY_ID = createField(DSL.name("mangopay_id"), SQLDataType.VARCHAR(10), this, "");

    /**
     * The column <code>applet.users_copy.wallet_id</code>.
     */
    public final TableField<UsersCopyRecord, String> WALLET_ID = createField(DSL.name("wallet_id"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>applet.users_copy.card_id</code>.
     */
    public final TableField<UsersCopyRecord, String> CARD_ID = createField(DSL.name("card_id"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>applet.users_copy.registration_data</code>.
     */
    public final TableField<UsersCopyRecord, String> REGISTRATION_DATA = createField(DSL.name("registration_data"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>applet.users_copy.access_key</code>.
     */
    public final TableField<UsersCopyRecord, String> ACCESS_KEY = createField(DSL.name("access_key"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>applet.users_copy.card_register_data_id</code>.
     */
    public final TableField<UsersCopyRecord, String> CARD_REGISTER_DATA_ID = createField(DSL.name("card_register_data_id"), SQLDataType.VARCHAR(10), this, "");

    /**
     * The column <code>applet.users_copy.card_registration_url</code>.
     */
    public final TableField<UsersCopyRecord, String> CARD_REGISTRATION_URL = createField(DSL.name("card_registration_url"), SQLDataType.VARCHAR(150), this, "");

    /**
     * The column <code>applet.users_copy.card_number</code>.
     */
    public final TableField<UsersCopyRecord, String> CARD_NUMBER = createField(DSL.name("card_number"), SQLDataType.VARCHAR(4), this, "");

    /**
     * The column <code>applet.users_copy.card_expiration_date</code>.
     */
    public final TableField<UsersCopyRecord, String> CARD_EXPIRATION_DATE = createField(DSL.name("card_expiration_date"), SQLDataType.VARCHAR(4), this, "");

    /**
     * The column <code>applet.users_copy.bank_account</code>.
     */
    public final TableField<UsersCopyRecord, String> BANK_ACCOUNT = createField(DSL.name("bank_account"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>applet.users_copy.bank_account_id</code>.
     */
    public final TableField<UsersCopyRecord, Integer> BANK_ACCOUNT_ID = createField(DSL.name("bank_account_id"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>applet.users_copy.birthday</code>.
     */
    public final TableField<UsersCopyRecord, LocalDate> BIRTHDAY = createField(DSL.name("birthday"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>applet.users_copy.nationality</code>.
     */
    public final TableField<UsersCopyRecord, String> NATIONALITY = createField(DSL.name("nationality"), SQLDataType.VARCHAR(2), this, "");

    /**
     * The column <code>applet.users_copy.country_of_residence</code>.
     */
    public final TableField<UsersCopyRecord, String> COUNTRY_OF_RESIDENCE = createField(DSL.name("country_of_residence"), SQLDataType.VARCHAR(2), this, "");

    /**
     * The column <code>applet.users_copy.nif</code>.
     */
    public final TableField<UsersCopyRecord, String> NIF = createField(DSL.name("nif"), SQLDataType.VARCHAR(10), this, "");

    /**
     * The column <code>applet.users_copy.address</code>.
     */
    public final TableField<UsersCopyRecord, String> ADDRESS = createField(DSL.name("address"), SQLDataType.VARCHAR(150), this, "");

    /**
     * The column <code>applet.users_copy.city</code>.
     */
    public final TableField<UsersCopyRecord, String> CITY = createField(DSL.name("city"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>applet.users_copy.postal_code</code>.
     */
    public final TableField<UsersCopyRecord, String> POSTAL_CODE = createField(DSL.name("postal_code"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>applet.users_copy.image_uri</code>.
     */
    public final TableField<UsersCopyRecord, String> IMAGE_URI = createField(DSL.name("image_uri"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.users_copy.header_uri</code>.
     */
    public final TableField<UsersCopyRecord, String> HEADER_URI = createField(DSL.name("header_uri"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>applet.users_copy.advert_published_count</code>.
     */
    public final TableField<UsersCopyRecord, Integer> ADVERT_PUBLISHED_COUNT = createField(DSL.name("advert_published_count"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>applet.users_copy.advert_count</code>.
     */
    public final TableField<UsersCopyRecord, Integer> ADVERT_COUNT = createField(DSL.name("advert_count"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>applet.users_copy.end_date</code>.
     */
    public final TableField<UsersCopyRecord, LocalDate> END_DATE = createField(DSL.name("end_date"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>applet.users_copy.notification_messages</code>.
     */
    public final TableField<UsersCopyRecord, Byte> NOTIFICATION_MESSAGES = createField(DSL.name("notification_messages"), SQLDataType.TINYINT.nullable(false).defaultValue(DSL.inline("1", SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>applet.users_copy.notification_adverts</code>.
     */
    public final TableField<UsersCopyRecord, Byte> NOTIFICATION_ADVERTS = createField(DSL.name("notification_adverts"), SQLDataType.TINYINT.nullable(false).defaultValue(DSL.inline("1", SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>applet.users_copy.alert_radius</code>.
     */
    public final TableField<UsersCopyRecord, Integer> ALERT_RADIUS = createField(DSL.name("alert_radius"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("40", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>applet.users_copy.language</code>.
     */
    public final TableField<UsersCopyRecord, String> LANGUAGE = createField(DSL.name("language"), SQLDataType.VARCHAR(2).nullable(false).defaultValue(DSL.inline("es", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>applet.users_copy.stripe_account_id</code>.
     */
    public final TableField<UsersCopyRecord, String> STRIPE_ACCOUNT_ID = createField(DSL.name("stripe_account_id"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>applet.users_copy.created</code>.
     */
    public final TableField<UsersCopyRecord, LocalDateTime> CREATED = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column <code>applet.users_copy.modified</code>.
     */
    public final TableField<UsersCopyRecord, LocalDateTime> MODIFIED = createField(DSL.name("modified"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column <code>applet.users_copy.created_at</code>.
     */
    public final TableField<UsersCopyRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column <code>applet.users_copy.updated_at</code>.
     */
    public final TableField<UsersCopyRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(0), this, "");

    private UsersCopy(Name alias, Table<UsersCopyRecord> aliased) {
        this(alias, aliased, null);
    }

    private UsersCopy(Name alias, Table<UsersCopyRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>applet.users_copy</code> table reference
     */
    public UsersCopy(String alias) {
        this(DSL.name(alias), USERS_COPY);
    }

    /**
     * Create an aliased <code>applet.users_copy</code> table reference
     */
    public UsersCopy(Name alias) {
        this(alias, USERS_COPY);
    }

    /**
     * Create a <code>applet.users_copy</code> table reference
     */
    public UsersCopy() {
        this(DSL.name("users_copy"), null);
    }

    public <O extends Record> UsersCopy(Table<O> child, ForeignKey<O, UsersCopyRecord> key) {
        super(child, key, USERS_COPY);
    }

    @Override
    public Schema getSchema() {
        return Applet.APPLET;
    }

    @Override
    public UsersCopy as(String alias) {
        return new UsersCopy(DSL.name(alias), this);
    }

    @Override
    public UsersCopy as(Name alias) {
        return new UsersCopy(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UsersCopy rename(String name) {
        return new UsersCopy(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UsersCopy rename(Name name) {
        return new UsersCopy(name, null);
    }
}
