/*
 * This file is generated by jOOQ.
 */
package com.opac.scms;


import com.opac.scms.tables.Agencies;
import com.opac.scms.tables.Agents;
import com.opac.scms.tables.BackendUsers;
import com.opac.scms.tables.Chats;
import com.opac.scms.tables.ComplaintReasons;
import com.opac.scms.tables.Complaints;
import com.opac.scms.tables.Countries;
import com.opac.scms.tables.DeviceUsers;
import com.opac.scms.tables.FailedJobs;
import com.opac.scms.tables.HibernateSequence;
import com.opac.scms.tables.Listing;
import com.opac.scms.tables.ListingCategories;
import com.opac.scms.tables.ListingImages;
import com.opac.scms.tables.Messages;
import com.opac.scms.tables.Migrations;
import com.opac.scms.tables.NotificationDeviceUsers;
import com.opac.scms.tables.Notifications;
import com.opac.scms.tables.PasswordResets;
import com.opac.scms.tables.Payments;
import com.opac.scms.tables.Roles;
import com.opac.scms.tables.Settings;
import com.opac.scms.tables.UserRole;
import com.opac.scms.tables.Users;
import com.opac.scms.tables.UsersCopy;
import com.opac.scms.tables.VerifyAccount;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Applet extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>applet</code>
     */
    public static final Applet APPLET = new Applet();

    /**
     * The table <code>applet.agencies</code>.
     */
    public final Agencies AGENCIES = Agencies.AGENCIES;

    /**
     * The table <code>applet.agents</code>.
     */
    public final Agents AGENTS = Agents.AGENTS;

    /**
     * The table <code>applet.backend_users</code>.
     */
    public final BackendUsers BACKEND_USERS = BackendUsers.BACKEND_USERS;

    /**
     * The table <code>applet.chats</code>.
     */
    public final Chats CHATS = Chats.CHATS;

    /**
     * The table <code>applet.complaint_reasons</code>.
     */
    public final ComplaintReasons COMPLAINT_REASONS = ComplaintReasons.COMPLAINT_REASONS;

    /**
     * The table <code>applet.complaints</code>.
     */
    public final Complaints COMPLAINTS = Complaints.COMPLAINTS;

    /**
     * The table <code>applet.countries</code>.
     */
    public final Countries COUNTRIES = Countries.COUNTRIES;

    /**
     * The table <code>applet.device_users</code>.
     */
    public final DeviceUsers DEVICE_USERS = DeviceUsers.DEVICE_USERS;

    /**
     * The table <code>applet.failed_jobs</code>.
     */
    public final FailedJobs FAILED_JOBS = FailedJobs.FAILED_JOBS;

    /**
     * The table <code>applet.hibernate_sequence</code>.
     */
    public final HibernateSequence HIBERNATE_SEQUENCE = HibernateSequence.HIBERNATE_SEQUENCE;

    /**
     * The table <code>applet.listing</code>.
     */
    public final Listing LISTING = Listing.LISTING;

    /**
     * The table <code>applet.listing_categories</code>.
     */
    public final ListingCategories LISTING_CATEGORIES = ListingCategories.LISTING_CATEGORIES;

    /**
     * The table <code>applet.listing_images</code>.
     */
    public final ListingImages LISTING_IMAGES = ListingImages.LISTING_IMAGES;

    /**
     * The table <code>applet.messages</code>.
     */
    public final Messages MESSAGES = Messages.MESSAGES;

    /**
     * The table <code>applet.migrations</code>.
     */
    public final Migrations MIGRATIONS = Migrations.MIGRATIONS;

    /**
     * The table <code>applet.notification_device_users</code>.
     */
    public final NotificationDeviceUsers NOTIFICATION_DEVICE_USERS = NotificationDeviceUsers.NOTIFICATION_DEVICE_USERS;

    /**
     * The table <code>applet.notifications</code>.
     */
    public final Notifications NOTIFICATIONS = Notifications.NOTIFICATIONS;

    /**
     * The table <code>applet.password_resets</code>.
     */
    public final PasswordResets PASSWORD_RESETS = PasswordResets.PASSWORD_RESETS;

    /**
     * The table <code>applet.payments</code>.
     */
    public final Payments PAYMENTS = Payments.PAYMENTS;

    /**
     * The table <code>applet.roles</code>.
     */
    public final Roles ROLES = Roles.ROLES;

    /**
     * The table <code>applet.settings</code>.
     */
    public final Settings SETTINGS = Settings.SETTINGS;

    /**
     * The table <code>applet.user_role</code>.
     */
    public final UserRole USER_ROLE = UserRole.USER_ROLE;

    /**
     * The table <code>applet.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * The table <code>applet.users_copy</code>.
     */
    public final UsersCopy USERS_COPY = UsersCopy.USERS_COPY;

    /**
     * The table <code>applet.verify_account</code>.
     */
    public final VerifyAccount VERIFY_ACCOUNT = VerifyAccount.VERIFY_ACCOUNT;

    /**
     * No further instances allowed
     */
    private Applet() {
        super("applet", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Agencies.AGENCIES,
            Agents.AGENTS,
            BackendUsers.BACKEND_USERS,
            Chats.CHATS,
            ComplaintReasons.COMPLAINT_REASONS,
            Complaints.COMPLAINTS,
            Countries.COUNTRIES,
            DeviceUsers.DEVICE_USERS,
            FailedJobs.FAILED_JOBS,
            HibernateSequence.HIBERNATE_SEQUENCE,
            Listing.LISTING,
            ListingCategories.LISTING_CATEGORIES,
            ListingImages.LISTING_IMAGES,
            Messages.MESSAGES,
            Migrations.MIGRATIONS,
            NotificationDeviceUsers.NOTIFICATION_DEVICE_USERS,
            Notifications.NOTIFICATIONS,
            PasswordResets.PASSWORD_RESETS,
            Payments.PAYMENTS,
            Roles.ROLES,
            Settings.SETTINGS,
            UserRole.USER_ROLE,
            Users.USERS,
            UsersCopy.USERS_COPY,
            VerifyAccount.VERIFY_ACCOUNT);
    }
}
