/*
 * This file is generated by jOOQ.
 */
package com.opac.scms;


import com.opac.scms.tables.Chats;
import com.opac.scms.tables.DeviceUsers;
import com.opac.scms.tables.Listing;
import com.opac.scms.tables.Messages;
import com.opac.scms.tables.PasswordResets;
import com.opac.scms.tables.Payments;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in applet.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index LISTING_ADVERT_CATEGORY_ID = Internal.createIndex(DSL.name("advert_category_id"), Listing.LISTING, new OrderField[] { Listing.LISTING.ADVERT_CATEGORY_ID }, false);
    public static final Index MESSAGES_CHAT_ID = Internal.createIndex(DSL.name("chat_id"), Messages.MESSAGES, new OrderField[] { Messages.MESSAGES.CHAT_ID }, false);
    public static final Index LISTING_LISTING_CATEGORY_ID = Internal.createIndex(DSL.name("listing_category_id"), Listing.LISTING, new OrderField[] { Listing.LISTING.LISTING_CATEGORY_ID }, false);
    public static final Index PASSWORD_RESETS_PASSWORD_RESETS_EMAIL_INDEX = Internal.createIndex(DSL.name("password_resets_email_index"), PasswordResets.PASSWORD_RESETS, new OrderField[] { PasswordResets.PASSWORD_RESETS.EMAIL }, false);
    public static final Index CHATS_USER_ID = Internal.createIndex(DSL.name("user_id"), Chats.CHATS, new OrderField[] { Chats.CHATS.USER_ID }, false);
    public static final Index DEVICE_USERS_USER_ID = Internal.createIndex(DSL.name("user_id"), DeviceUsers.DEVICE_USERS, new OrderField[] { DeviceUsers.DEVICE_USERS.USER_ID }, false);
    public static final Index LISTING_USER_ID = Internal.createIndex(DSL.name("user_id"), Listing.LISTING, new OrderField[] { Listing.LISTING.USER_ID }, false);
    public static final Index PAYMENTS_USER_ID = Internal.createIndex(DSL.name("user_id"), Payments.PAYMENTS, new OrderField[] { Payments.PAYMENTS.USER_ID }, false);
}
