/*
 * This file is generated by jOOQ.
 */
package com.opac.scms;


import com.opac.scms.tables.Agencies;
import com.opac.scms.tables.Agents;
import com.opac.scms.tables.BackendUsers;
import com.opac.scms.tables.Chats;
import com.opac.scms.tables.ComplaintReasons;
import com.opac.scms.tables.Complaints;
import com.opac.scms.tables.Countries;
import com.opac.scms.tables.DeviceUsers;
import com.opac.scms.tables.FailedJobs;
import com.opac.scms.tables.HibernateSequence;
import com.opac.scms.tables.Listing;
import com.opac.scms.tables.ListingCategories;
import com.opac.scms.tables.ListingImages;
import com.opac.scms.tables.Messages;
import com.opac.scms.tables.Migrations;
import com.opac.scms.tables.NotificationDeviceUsers;
import com.opac.scms.tables.Notifications;
import com.opac.scms.tables.PasswordResets;
import com.opac.scms.tables.Payments;
import com.opac.scms.tables.Roles;
import com.opac.scms.tables.Settings;
import com.opac.scms.tables.UserRole;
import com.opac.scms.tables.Users;
import com.opac.scms.tables.UsersCopy;
import com.opac.scms.tables.VerifyAccount;


/**
 * Convenience access to all tables in applet.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>applet.agencies</code>.
     */
    public static final Agencies AGENCIES = Agencies.AGENCIES;

    /**
     * The table <code>applet.agents</code>.
     */
    public static final Agents AGENTS = Agents.AGENTS;

    /**
     * The table <code>applet.backend_users</code>.
     */
    public static final BackendUsers BACKEND_USERS = BackendUsers.BACKEND_USERS;

    /**
     * The table <code>applet.chats</code>.
     */
    public static final Chats CHATS = Chats.CHATS;

    /**
     * The table <code>applet.complaint_reasons</code>.
     */
    public static final ComplaintReasons COMPLAINT_REASONS = ComplaintReasons.COMPLAINT_REASONS;

    /**
     * The table <code>applet.complaints</code>.
     */
    public static final Complaints COMPLAINTS = Complaints.COMPLAINTS;

    /**
     * The table <code>applet.countries</code>.
     */
    public static final Countries COUNTRIES = Countries.COUNTRIES;

    /**
     * The table <code>applet.device_users</code>.
     */
    public static final DeviceUsers DEVICE_USERS = DeviceUsers.DEVICE_USERS;

    /**
     * The table <code>applet.failed_jobs</code>.
     */
    public static final FailedJobs FAILED_JOBS = FailedJobs.FAILED_JOBS;

    /**
     * The table <code>applet.hibernate_sequence</code>.
     */
    public static final HibernateSequence HIBERNATE_SEQUENCE = HibernateSequence.HIBERNATE_SEQUENCE;

    /**
     * The table <code>applet.listing</code>.
     */
    public static final Listing LISTING = Listing.LISTING;

    /**
     * The table <code>applet.listing_categories</code>.
     */
    public static final ListingCategories LISTING_CATEGORIES = ListingCategories.LISTING_CATEGORIES;

    /**
     * The table <code>applet.listing_images</code>.
     */
    public static final ListingImages LISTING_IMAGES = ListingImages.LISTING_IMAGES;

    /**
     * The table <code>applet.messages</code>.
     */
    public static final Messages MESSAGES = Messages.MESSAGES;

    /**
     * The table <code>applet.migrations</code>.
     */
    public static final Migrations MIGRATIONS = Migrations.MIGRATIONS;

    /**
     * The table <code>applet.notification_device_users</code>.
     */
    public static final NotificationDeviceUsers NOTIFICATION_DEVICE_USERS = NotificationDeviceUsers.NOTIFICATION_DEVICE_USERS;

    /**
     * The table <code>applet.notifications</code>.
     */
    public static final Notifications NOTIFICATIONS = Notifications.NOTIFICATIONS;

    /**
     * The table <code>applet.password_resets</code>.
     */
    public static final PasswordResets PASSWORD_RESETS = PasswordResets.PASSWORD_RESETS;

    /**
     * The table <code>applet.payments</code>.
     */
    public static final Payments PAYMENTS = Payments.PAYMENTS;

    /**
     * The table <code>applet.roles</code>.
     */
    public static final Roles ROLES = Roles.ROLES;

    /**
     * The table <code>applet.settings</code>.
     */
    public static final Settings SETTINGS = Settings.SETTINGS;

    /**
     * The table <code>applet.user_role</code>.
     */
    public static final UserRole USER_ROLE = UserRole.USER_ROLE;

    /**
     * The table <code>applet.users</code>.
     */
    public static final Users USERS = Users.USERS;

    /**
     * The table <code>applet.users_copy</code>.
     */
    public static final UsersCopy USERS_COPY = UsersCopy.USERS_COPY;

    /**
     * The table <code>applet.verify_account</code>.
     */
    public static final VerifyAccount VERIFY_ACCOUNT = VerifyAccount.VERIFY_ACCOUNT;
}
