/*
 * This file is generated by jOOQ.
 */
package com.opac.scms.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum ComplaintReasonsType implements EnumType {

    ANUNCIO("ANUNCIO"),

    USUARIO("USUARIO");

    private final String literal;

    private ComplaintReasonsType(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return "complaint_reasons_type";
    }

    @Override
    public String getLiteral() {
        return literal;
    }
}
