/*
 * This file is generated by jOOQ.
 */
package com.opac.scms.tables.records;


import com.opac.scms.tables.Agencies;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AgenciesRecord extends TableRecordImpl<AgenciesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>applet.agencies.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>applet.agencies.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>applet.agencies.firm_name</code>.
     */
    public void setFirmName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>applet.agencies.firm_name</code>.
     */
    public String getFirmName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>applet.agencies.npn</code>.
     */
    public void setNpn(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>applet.agencies.npn</code>.
     */
    public String getNpn() {
        return (String) get(2);
    }

    /**
     * Setter for <code>applet.agencies.license_number</code>.
     */
    public void setLicenseNumber(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>applet.agencies.license_number</code>.
     */
    public String getLicenseNumber() {
        return (String) get(3);
    }

    /**
     * Setter for <code>applet.agencies.license_state</code>.
     */
    public void setLicenseState(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>applet.agencies.license_state</code>.
     */
    public String getLicenseState() {
        return (String) get(4);
    }

    /**
     * Setter for <code>applet.agencies.email_address</code>.
     */
    public void setEmailAddress(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>applet.agencies.email_address</code>.
     */
    public String getEmailAddress() {
        return (String) get(5);
    }

    /**
     * Setter for <code>applet.agencies.email_domain</code>.
     */
    public void setEmailDomain(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>applet.agencies.email_domain</code>.
     */
    public String getEmailDomain() {
        return (String) get(6);
    }

    /**
     * Setter for <code>applet.agencies.email_personal</code>.
     */
    public void setEmailPersonal(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>applet.agencies.email_personal</code>.
     */
    public String getEmailPersonal() {
        return (String) get(7);
    }

    /**
     * Setter for <code>applet.agencies.businessphone</code>.
     */
    public void setBusinessphone(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>applet.agencies.businessphone</code>.
     */
    public String getBusinessphone() {
        return (String) get(8);
    }

    /**
     * Setter for <code>applet.agencies.business_address1</code>.
     */
    public void setBusinessAddress1(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>applet.agencies.business_address1</code>.
     */
    public String getBusinessAddress1() {
        return (String) get(9);
    }

    /**
     * Setter for <code>applet.agencies.business_address2</code>.
     */
    public void setBusinessAddress2(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>applet.agencies.business_address2</code>.
     */
    public String getBusinessAddress2() {
        return (String) get(10);
    }

    /**
     * Setter for <code>applet.agencies.business_city</code>.
     */
    public void setBusinessCity(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>applet.agencies.business_city</code>.
     */
    public String getBusinessCity() {
        return (String) get(11);
    }

    /**
     * Setter for <code>applet.agencies.business_state</code>.
     */
    public void setBusinessState(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>applet.agencies.business_state</code>.
     */
    public String getBusinessState() {
        return (String) get(12);
    }

    /**
     * Setter for <code>applet.agencies.business_zip</code>.
     */
    public void setBusinessZip(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>applet.agencies.business_zip</code>.
     */
    public String getBusinessZip() {
        return (String) get(13);
    }

    /**
     * Setter for <code>applet.agencies.business_zip_without_postal_code</code>.
     */
    public void setBusinessZipWithoutPostalCode(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>applet.agencies.business_zip_without_postal_code</code>.
     */
    public String getBusinessZipWithoutPostalCode() {
        return (String) get(14);
    }

    /**
     * Setter for <code>applet.agencies.Full_Address_WA</code>.
     */
    public void setFullAddressWa(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>applet.agencies.Full_Address_WA</code>.
     */
    public String getFullAddressWa() {
        return (String) get(15);
    }

    /**
     * Setter for <code>applet.agencies.Google_Formatted_Address</code>.
     */
    public void setGoogleFormattedAddress(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>applet.agencies.Google_Formatted_Address</code>.
     */
    public String getGoogleFormattedAddress() {
        return (String) get(16);
    }

    /**
     * Setter for <code>applet.agencies.Google_Latitude</code>.
     */
    public void setGoogleLatitude(BigDecimal value) {
        set(17, value);
    }

    /**
     * Getter for <code>applet.agencies.Google_Latitude</code>.
     */
    public BigDecimal getGoogleLatitude() {
        return (BigDecimal) get(17);
    }

    /**
     * Setter for <code>applet.agencies.Google_Longitude</code>.
     */
    public void setGoogleLongitude(BigDecimal value) {
        set(18, value);
    }

    /**
     * Getter for <code>applet.agencies.Google_Longitude</code>.
     */
    public BigDecimal getGoogleLongitude() {
        return (BigDecimal) get(18);
    }

    /**
     * Setter for <code>applet.agencies.Type</code>.
     */
    public void setType(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>applet.agencies.Type</code>.
     */
    public String getType() {
        return (String) get(19);
    }

    /**
     * Setter for <code>applet.agencies.Use_Record_For_Lat_Long</code>.
     */
    public void setUseRecordForLatLong(Integer value) {
        set(20, value);
    }

    /**
     * Getter for <code>applet.agencies.Use_Record_For_Lat_Long</code>.
     */
    public Integer getUseRecordForLatLong() {
        return (Integer) get(20);
    }

    /**
     * Setter for <code>applet.agencies.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(21, value);
    }

    /**
     * Getter for <code>applet.agencies.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(21);
    }

    /**
     * Setter for <code>applet.agencies.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(22, value);
    }

    /**
     * Getter for <code>applet.agencies.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(22);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AgenciesRecord
     */
    public AgenciesRecord() {
        super(Agencies.AGENCIES);
    }

    /**
     * Create a detached, initialised AgenciesRecord
     */
    public AgenciesRecord(Integer id, String firmName, String npn, String licenseNumber, String licenseState, String emailAddress, String emailDomain, String emailPersonal, String businessphone, String businessAddress1, String businessAddress2, String businessCity, String businessState, String businessZip, String businessZipWithoutPostalCode, String fullAddressWa, String googleFormattedAddress, BigDecimal googleLatitude, BigDecimal googleLongitude, String type, Integer useRecordForLatLong, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(Agencies.AGENCIES);

        setId(id);
        setFirmName(firmName);
        setNpn(npn);
        setLicenseNumber(licenseNumber);
        setLicenseState(licenseState);
        setEmailAddress(emailAddress);
        setEmailDomain(emailDomain);
        setEmailPersonal(emailPersonal);
        setBusinessphone(businessphone);
        setBusinessAddress1(businessAddress1);
        setBusinessAddress2(businessAddress2);
        setBusinessCity(businessCity);
        setBusinessState(businessState);
        setBusinessZip(businessZip);
        setBusinessZipWithoutPostalCode(businessZipWithoutPostalCode);
        setFullAddressWa(fullAddressWa);
        setGoogleFormattedAddress(googleFormattedAddress);
        setGoogleLatitude(googleLatitude);
        setGoogleLongitude(googleLongitude);
        setType(type);
        setUseRecordForLatLong(useRecordForLatLong);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
    }
}
