/*
 * This file is generated by jOOQ.
 */
package com.opac.scms.tables.records;


import com.opac.scms.tables.Chats;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChatsRecord extends UpdatableRecordImpl<ChatsRecord> implements Record5<Integer, Integer, Integer, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>applet.chats.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>applet.chats.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>applet.chats.advert_id</code>.
     */
    public void setAdvertId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>applet.chats.advert_id</code>.
     */
    public Integer getAdvertId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>applet.chats.user_id</code>. usuario q inicia el chat
     */
    public void setUserId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>applet.chats.user_id</code>. usuario q inicia el chat
     */
    public Integer getUserId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>applet.chats.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>applet.chats.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>applet.chats.modified</code>.
     */
    public void setModified(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>applet.chats.modified</code>.
     */
    public LocalDateTime getModified() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Integer, Integer, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Integer, Integer, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Chats.CHATS.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Chats.CHATS.ADVERT_ID;
    }

    @Override
    public Field<Integer> field3() {
        return Chats.CHATS.USER_ID;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return Chats.CHATS.CREATED;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Chats.CHATS.MODIFIED;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getAdvertId();
    }

    @Override
    public Integer component3() {
        return getUserId();
    }

    @Override
    public LocalDateTime component4() {
        return getCreated();
    }

    @Override
    public LocalDateTime component5() {
        return getModified();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getAdvertId();
    }

    @Override
    public Integer value3() {
        return getUserId();
    }

    @Override
    public LocalDateTime value4() {
        return getCreated();
    }

    @Override
    public LocalDateTime value5() {
        return getModified();
    }

    @Override
    public ChatsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ChatsRecord value2(Integer value) {
        setAdvertId(value);
        return this;
    }

    @Override
    public ChatsRecord value3(Integer value) {
        setUserId(value);
        return this;
    }

    @Override
    public ChatsRecord value4(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public ChatsRecord value5(LocalDateTime value) {
        setModified(value);
        return this;
    }

    @Override
    public ChatsRecord values(Integer value1, Integer value2, Integer value3, LocalDateTime value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ChatsRecord
     */
    public ChatsRecord() {
        super(Chats.CHATS);
    }

    /**
     * Create a detached, initialised ChatsRecord
     */
    public ChatsRecord(Integer id, Integer advertId, Integer userId, LocalDateTime created, LocalDateTime modified) {
        super(Chats.CHATS);

        setId(id);
        setAdvertId(advertId);
        setUserId(userId);
        setCreated(created);
        setModified(modified);
    }
}
