/*
 * This file is generated by jOOQ.
 */
package com.opac.scms.tables.records;


import com.opac.scms.enums.ComplaintReasonsType;
import com.opac.scms.tables.ComplaintReasons;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ComplaintReasonsRecord extends UpdatableRecordImpl<ComplaintReasonsRecord> implements Record6<Integer, ComplaintReasonsType, String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>applet.complaint_reasons.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>applet.complaint_reasons.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>applet.complaint_reasons.type</code>.
     */
    public void setType(ComplaintReasonsType value) {
        set(1, value);
    }

    /**
     * Getter for <code>applet.complaint_reasons.type</code>.
     */
    public ComplaintReasonsType getType() {
        return (ComplaintReasonsType) get(1);
    }

    /**
     * Setter for <code>applet.complaint_reasons.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>applet.complaint_reasons.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>applet.complaint_reasons.description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>applet.complaint_reasons.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>applet.complaint_reasons.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>applet.complaint_reasons.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>applet.complaint_reasons.modified</code>.
     */
    public void setModified(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>applet.complaint_reasons.modified</code>.
     */
    public LocalDateTime getModified() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, ComplaintReasonsType, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, ComplaintReasonsType, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ComplaintReasons.COMPLAINT_REASONS.ID;
    }

    @Override
    public Field<ComplaintReasonsType> field2() {
        return ComplaintReasons.COMPLAINT_REASONS.TYPE;
    }

    @Override
    public Field<String> field3() {
        return ComplaintReasons.COMPLAINT_REASONS.NAME;
    }

    @Override
    public Field<String> field4() {
        return ComplaintReasons.COMPLAINT_REASONS.DESCRIPTION;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return ComplaintReasons.COMPLAINT_REASONS.CREATED;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return ComplaintReasons.COMPLAINT_REASONS.MODIFIED;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public ComplaintReasonsType component2() {
        return getType();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public String component4() {
        return getDescription();
    }

    @Override
    public LocalDateTime component5() {
        return getCreated();
    }

    @Override
    public LocalDateTime component6() {
        return getModified();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public ComplaintReasonsType value2() {
        return getType();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public String value4() {
        return getDescription();
    }

    @Override
    public LocalDateTime value5() {
        return getCreated();
    }

    @Override
    public LocalDateTime value6() {
        return getModified();
    }

    @Override
    public ComplaintReasonsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ComplaintReasonsRecord value2(ComplaintReasonsType value) {
        setType(value);
        return this;
    }

    @Override
    public ComplaintReasonsRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public ComplaintReasonsRecord value4(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public ComplaintReasonsRecord value5(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public ComplaintReasonsRecord value6(LocalDateTime value) {
        setModified(value);
        return this;
    }

    @Override
    public ComplaintReasonsRecord values(Integer value1, ComplaintReasonsType value2, String value3, String value4, LocalDateTime value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ComplaintReasonsRecord
     */
    public ComplaintReasonsRecord() {
        super(ComplaintReasons.COMPLAINT_REASONS);
    }

    /**
     * Create a detached, initialised ComplaintReasonsRecord
     */
    public ComplaintReasonsRecord(Integer id, ComplaintReasonsType type, String name, String description, LocalDateTime created, LocalDateTime modified) {
        super(ComplaintReasons.COMPLAINT_REASONS);

        setId(id);
        setType(type);
        setName(name);
        setDescription(description);
        setCreated(created);
        setModified(modified);
    }
}
