/*
 * This file is generated by jOOQ.
 */
package com.opac.scms.tables.records;


import com.opac.scms.tables.DeviceUsers;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DeviceUsersRecord extends UpdatableRecordImpl<DeviceUsersRecord> implements Record11<Integer, Integer, String, String, Byte, BigDecimal, BigDecimal, LocalDateTime, Byte, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>applet.device_users.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>applet.device_users.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>applet.device_users.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>applet.device_users.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>applet.device_users.device</code>.
     */
    public void setDevice(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>applet.device_users.device</code>.
     */
    public String getDevice() {
        return (String) get(2);
    }

    /**
     * Setter for <code>applet.device_users.device_ui</code>.
     */
    public void setDeviceUi(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>applet.device_users.device_ui</code>.
     */
    public String getDeviceUi() {
        return (String) get(3);
    }

    /**
     * Setter for <code>applet.device_users.os_type</code>.
     */
    public void setOsType(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>applet.device_users.os_type</code>.
     */
    public Byte getOsType() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>applet.device_users.last_location_latitude</code>.
     */
    public void setLastLocationLatitude(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>applet.device_users.last_location_latitude</code>.
     */
    public BigDecimal getLastLocationLatitude() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>applet.device_users.last_location_longitude</code>.
     */
    public void setLastLocationLongitude(BigDecimal value) {
        set(6, value);
    }

    /**
     * Getter for <code>applet.device_users.last_location_longitude</code>.
     */
    public BigDecimal getLastLocationLongitude() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>applet.device_users.last_connection</code>.
     */
    public void setLastConnection(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>applet.device_users.last_connection</code>.
     */
    public LocalDateTime getLastConnection() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>applet.device_users.notifications_state</code>.
     */
    public void setNotificationsState(Byte value) {
        set(8, value);
    }

    /**
     * Getter for <code>applet.device_users.notifications_state</code>.
     */
    public Byte getNotificationsState() {
        return (Byte) get(8);
    }

    /**
     * Setter for <code>applet.device_users.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>applet.device_users.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>applet.device_users.modified</code>.
     */
    public void setModified(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>applet.device_users.modified</code>.
     */
    public LocalDateTime getModified() {
        return (LocalDateTime) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<Integer, Integer, String, String, Byte, BigDecimal, BigDecimal, LocalDateTime, Byte, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<Integer, Integer, String, String, Byte, BigDecimal, BigDecimal, LocalDateTime, Byte, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return DeviceUsers.DEVICE_USERS.ID;
    }

    @Override
    public Field<Integer> field2() {
        return DeviceUsers.DEVICE_USERS.USER_ID;
    }

    @Override
    public Field<String> field3() {
        return DeviceUsers.DEVICE_USERS.DEVICE;
    }

    @Override
    public Field<String> field4() {
        return DeviceUsers.DEVICE_USERS.DEVICE_UI;
    }

    @Override
    public Field<Byte> field5() {
        return DeviceUsers.DEVICE_USERS.OS_TYPE;
    }

    @Override
    public Field<BigDecimal> field6() {
        return DeviceUsers.DEVICE_USERS.LAST_LOCATION_LATITUDE;
    }

    @Override
    public Field<BigDecimal> field7() {
        return DeviceUsers.DEVICE_USERS.LAST_LOCATION_LONGITUDE;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return DeviceUsers.DEVICE_USERS.LAST_CONNECTION;
    }

    @Override
    public Field<Byte> field9() {
        return DeviceUsers.DEVICE_USERS.NOTIFICATIONS_STATE;
    }

    @Override
    public Field<LocalDateTime> field10() {
        return DeviceUsers.DEVICE_USERS.CREATED;
    }

    @Override
    public Field<LocalDateTime> field11() {
        return DeviceUsers.DEVICE_USERS.MODIFIED;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getUserId();
    }

    @Override
    public String component3() {
        return getDevice();
    }

    @Override
    public String component4() {
        return getDeviceUi();
    }

    @Override
    public Byte component5() {
        return getOsType();
    }

    @Override
    public BigDecimal component6() {
        return getLastLocationLatitude();
    }

    @Override
    public BigDecimal component7() {
        return getLastLocationLongitude();
    }

    @Override
    public LocalDateTime component8() {
        return getLastConnection();
    }

    @Override
    public Byte component9() {
        return getNotificationsState();
    }

    @Override
    public LocalDateTime component10() {
        return getCreated();
    }

    @Override
    public LocalDateTime component11() {
        return getModified();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getUserId();
    }

    @Override
    public String value3() {
        return getDevice();
    }

    @Override
    public String value4() {
        return getDeviceUi();
    }

    @Override
    public Byte value5() {
        return getOsType();
    }

    @Override
    public BigDecimal value6() {
        return getLastLocationLatitude();
    }

    @Override
    public BigDecimal value7() {
        return getLastLocationLongitude();
    }

    @Override
    public LocalDateTime value8() {
        return getLastConnection();
    }

    @Override
    public Byte value9() {
        return getNotificationsState();
    }

    @Override
    public LocalDateTime value10() {
        return getCreated();
    }

    @Override
    public LocalDateTime value11() {
        return getModified();
    }

    @Override
    public DeviceUsersRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public DeviceUsersRecord value2(Integer value) {
        setUserId(value);
        return this;
    }

    @Override
    public DeviceUsersRecord value3(String value) {
        setDevice(value);
        return this;
    }

    @Override
    public DeviceUsersRecord value4(String value) {
        setDeviceUi(value);
        return this;
    }

    @Override
    public DeviceUsersRecord value5(Byte value) {
        setOsType(value);
        return this;
    }

    @Override
    public DeviceUsersRecord value6(BigDecimal value) {
        setLastLocationLatitude(value);
        return this;
    }

    @Override
    public DeviceUsersRecord value7(BigDecimal value) {
        setLastLocationLongitude(value);
        return this;
    }

    @Override
    public DeviceUsersRecord value8(LocalDateTime value) {
        setLastConnection(value);
        return this;
    }

    @Override
    public DeviceUsersRecord value9(Byte value) {
        setNotificationsState(value);
        return this;
    }

    @Override
    public DeviceUsersRecord value10(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public DeviceUsersRecord value11(LocalDateTime value) {
        setModified(value);
        return this;
    }

    @Override
    public DeviceUsersRecord values(Integer value1, Integer value2, String value3, String value4, Byte value5, BigDecimal value6, BigDecimal value7, LocalDateTime value8, Byte value9, LocalDateTime value10, LocalDateTime value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DeviceUsersRecord
     */
    public DeviceUsersRecord() {
        super(DeviceUsers.DEVICE_USERS);
    }

    /**
     * Create a detached, initialised DeviceUsersRecord
     */
    public DeviceUsersRecord(Integer id, Integer userId, String device, String deviceUi, Byte osType, BigDecimal lastLocationLatitude, BigDecimal lastLocationLongitude, LocalDateTime lastConnection, Byte notificationsState, LocalDateTime created, LocalDateTime modified) {
        super(DeviceUsers.DEVICE_USERS);

        setId(id);
        setUserId(userId);
        setDevice(device);
        setDeviceUi(deviceUi);
        setOsType(osType);
        setLastLocationLatitude(lastLocationLatitude);
        setLastLocationLongitude(lastLocationLongitude);
        setLastConnection(lastConnection);
        setNotificationsState(notificationsState);
        setCreated(created);
        setModified(modified);
    }
}
