/*
 * This file is generated by jOOQ.
 */
package com.opac.scms.tables.records;


import com.opac.scms.tables.FailedJobs;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FailedJobsRecord extends UpdatableRecordImpl<FailedJobsRecord> implements Record6<ULong, String, String, String, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>applet.failed_jobs.id</code>.
     */
    public void setId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>applet.failed_jobs.id</code>.
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>applet.failed_jobs.connection</code>.
     */
    public void setConnection(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>applet.failed_jobs.connection</code>.
     */
    public String getConnection() {
        return (String) get(1);
    }

    /**
     * Setter for <code>applet.failed_jobs.queue</code>.
     */
    public void setQueue(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>applet.failed_jobs.queue</code>.
     */
    public String getQueue() {
        return (String) get(2);
    }

    /**
     * Setter for <code>applet.failed_jobs.payload</code>.
     */
    public void setPayload(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>applet.failed_jobs.payload</code>.
     */
    public String getPayload() {
        return (String) get(3);
    }

    /**
     * Setter for <code>applet.failed_jobs.exception</code>.
     */
    public void setException(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>applet.failed_jobs.exception</code>.
     */
    public String getException() {
        return (String) get(4);
    }

    /**
     * Setter for <code>applet.failed_jobs.failed_at</code>.
     */
    public void setFailedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>applet.failed_jobs.failed_at</code>.
     */
    public LocalDateTime getFailedAt() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<ULong, String, String, String, String, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<ULong, String, String, String, String, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<ULong> field1() {
        return FailedJobs.FAILED_JOBS.ID;
    }

    @Override
    public Field<String> field2() {
        return FailedJobs.FAILED_JOBS.CONNECTION;
    }

    @Override
    public Field<String> field3() {
        return FailedJobs.FAILED_JOBS.QUEUE;
    }

    @Override
    public Field<String> field4() {
        return FailedJobs.FAILED_JOBS.PAYLOAD;
    }

    @Override
    public Field<String> field5() {
        return FailedJobs.FAILED_JOBS.EXCEPTION;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return FailedJobs.FAILED_JOBS.FAILED_AT;
    }

    @Override
    public ULong component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getConnection();
    }

    @Override
    public String component3() {
        return getQueue();
    }

    @Override
    public String component4() {
        return getPayload();
    }

    @Override
    public String component5() {
        return getException();
    }

    @Override
    public LocalDateTime component6() {
        return getFailedAt();
    }

    @Override
    public ULong value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getConnection();
    }

    @Override
    public String value3() {
        return getQueue();
    }

    @Override
    public String value4() {
        return getPayload();
    }

    @Override
    public String value5() {
        return getException();
    }

    @Override
    public LocalDateTime value6() {
        return getFailedAt();
    }

    @Override
    public FailedJobsRecord value1(ULong value) {
        setId(value);
        return this;
    }

    @Override
    public FailedJobsRecord value2(String value) {
        setConnection(value);
        return this;
    }

    @Override
    public FailedJobsRecord value3(String value) {
        setQueue(value);
        return this;
    }

    @Override
    public FailedJobsRecord value4(String value) {
        setPayload(value);
        return this;
    }

    @Override
    public FailedJobsRecord value5(String value) {
        setException(value);
        return this;
    }

    @Override
    public FailedJobsRecord value6(LocalDateTime value) {
        setFailedAt(value);
        return this;
    }

    @Override
    public FailedJobsRecord values(ULong value1, String value2, String value3, String value4, String value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FailedJobsRecord
     */
    public FailedJobsRecord() {
        super(FailedJobs.FAILED_JOBS);
    }

    /**
     * Create a detached, initialised FailedJobsRecord
     */
    public FailedJobsRecord(ULong id, String connection, String queue, String payload, String exception, LocalDateTime failedAt) {
        super(FailedJobs.FAILED_JOBS);

        setId(id);
        setConnection(connection);
        setQueue(queue);
        setPayload(payload);
        setException(exception);
        setFailedAt(failedAt);
    }
}
