/*
 * This file is generated by jOOQ.
 */
package com.opac.scms.tables.records;


import com.opac.scms.tables.ListingImages;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ListingImagesRecord extends TableRecordImpl<ListingImagesRecord> implements Record5<Integer, Integer, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>applet.listing_images.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>applet.listing_images.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>applet.listing_images.advert_id</code>.
     */
    public void setAdvertId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>applet.listing_images.advert_id</code>.
     */
    public Integer getAdvertId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>applet.listing_images.uri</code>.
     */
    public void setUri(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>applet.listing_images.uri</code>.
     */
    public String getUri() {
        return (String) get(2);
    }

    /**
     * Setter for <code>applet.listing_images.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>applet.listing_images.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>applet.listing_images.modified</code>.
     */
    public void setModified(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>applet.listing_images.modified</code>.
     */
    public LocalDateTime getModified() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Integer, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Integer, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ListingImages.LISTING_IMAGES.ID;
    }

    @Override
    public Field<Integer> field2() {
        return ListingImages.LISTING_IMAGES.ADVERT_ID;
    }

    @Override
    public Field<String> field3() {
        return ListingImages.LISTING_IMAGES.URI;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return ListingImages.LISTING_IMAGES.CREATED;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return ListingImages.LISTING_IMAGES.MODIFIED;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getAdvertId();
    }

    @Override
    public String component3() {
        return getUri();
    }

    @Override
    public LocalDateTime component4() {
        return getCreated();
    }

    @Override
    public LocalDateTime component5() {
        return getModified();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getAdvertId();
    }

    @Override
    public String value3() {
        return getUri();
    }

    @Override
    public LocalDateTime value4() {
        return getCreated();
    }

    @Override
    public LocalDateTime value5() {
        return getModified();
    }

    @Override
    public ListingImagesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ListingImagesRecord value2(Integer value) {
        setAdvertId(value);
        return this;
    }

    @Override
    public ListingImagesRecord value3(String value) {
        setUri(value);
        return this;
    }

    @Override
    public ListingImagesRecord value4(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public ListingImagesRecord value5(LocalDateTime value) {
        setModified(value);
        return this;
    }

    @Override
    public ListingImagesRecord values(Integer value1, Integer value2, String value3, LocalDateTime value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ListingImagesRecord
     */
    public ListingImagesRecord() {
        super(ListingImages.LISTING_IMAGES);
    }

    /**
     * Create a detached, initialised ListingImagesRecord
     */
    public ListingImagesRecord(Integer id, Integer advertId, String uri, LocalDateTime created, LocalDateTime modified) {
        super(ListingImages.LISTING_IMAGES);

        setId(id);
        setAdvertId(advertId);
        setUri(uri);
        setCreated(created);
        setModified(modified);
    }
}
