/*
 * This file is generated by jOOQ.
 */
package com.opac.scms.tables.records;


import com.opac.scms.tables.ListingCategories;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ListingCategoriesRecord extends UpdatableRecordImpl<ListingCategoriesRecord> implements Record7<Integer, String, String, Integer, Integer, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>applet.listing_categories.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>applet.listing_categories.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>applet.listing_categories.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>applet.listing_categories.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>applet.listing_categories.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>applet.listing_categories.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>applet.listing_categories.advert_published_count</code>.
     */
    public void setAdvertPublishedCount(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>applet.listing_categories.advert_published_count</code>.
     */
    public Integer getAdvertPublishedCount() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>applet.listing_categories.advert_count</code>.
     */
    public void setAdvertCount(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>applet.listing_categories.advert_count</code>.
     */
    public Integer getAdvertCount() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>applet.listing_categories.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>applet.listing_categories.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>applet.listing_categories.modified</code>.
     */
    public void setModified(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>applet.listing_categories.modified</code>.
     */
    public LocalDateTime getModified() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, String, String, Integer, Integer, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, String, String, Integer, Integer, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ListingCategories.LISTING_CATEGORIES.ID;
    }

    @Override
    public Field<String> field2() {
        return ListingCategories.LISTING_CATEGORIES.NAME;
    }

    @Override
    public Field<String> field3() {
        return ListingCategories.LISTING_CATEGORIES.DESCRIPTION;
    }

    @Override
    public Field<Integer> field4() {
        return ListingCategories.LISTING_CATEGORIES.ADVERT_PUBLISHED_COUNT;
    }

    @Override
    public Field<Integer> field5() {
        return ListingCategories.LISTING_CATEGORIES.ADVERT_COUNT;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return ListingCategories.LISTING_CATEGORIES.CREATED;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return ListingCategories.LISTING_CATEGORIES.MODIFIED;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getDescription();
    }

    @Override
    public Integer component4() {
        return getAdvertPublishedCount();
    }

    @Override
    public Integer component5() {
        return getAdvertCount();
    }

    @Override
    public LocalDateTime component6() {
        return getCreated();
    }

    @Override
    public LocalDateTime component7() {
        return getModified();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getDescription();
    }

    @Override
    public Integer value4() {
        return getAdvertPublishedCount();
    }

    @Override
    public Integer value5() {
        return getAdvertCount();
    }

    @Override
    public LocalDateTime value6() {
        return getCreated();
    }

    @Override
    public LocalDateTime value7() {
        return getModified();
    }

    @Override
    public ListingCategoriesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ListingCategoriesRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public ListingCategoriesRecord value3(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public ListingCategoriesRecord value4(Integer value) {
        setAdvertPublishedCount(value);
        return this;
    }

    @Override
    public ListingCategoriesRecord value5(Integer value) {
        setAdvertCount(value);
        return this;
    }

    @Override
    public ListingCategoriesRecord value6(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public ListingCategoriesRecord value7(LocalDateTime value) {
        setModified(value);
        return this;
    }

    @Override
    public ListingCategoriesRecord values(Integer value1, String value2, String value3, Integer value4, Integer value5, LocalDateTime value6, LocalDateTime value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ListingCategoriesRecord
     */
    public ListingCategoriesRecord() {
        super(ListingCategories.LISTING_CATEGORIES);
    }

    /**
     * Create a detached, initialised ListingCategoriesRecord
     */
    public ListingCategoriesRecord(Integer id, String name, String description, Integer advertPublishedCount, Integer advertCount, LocalDateTime created, LocalDateTime modified) {
        super(ListingCategories.LISTING_CATEGORIES);

        setId(id);
        setName(name);
        setDescription(description);
        setAdvertPublishedCount(advertPublishedCount);
        setAdvertCount(advertCount);
        setCreated(created);
        setModified(modified);
    }
}
