/*
 * This file is generated by jOOQ.
 */
package com.opac.scms.tables.records;


import com.opac.scms.tables.Migrations;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MigrationsRecord extends UpdatableRecordImpl<MigrationsRecord> implements Record3<UInteger, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>applet.migrations.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>applet.migrations.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>applet.migrations.migration</code>.
     */
    public void setMigration(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>applet.migrations.migration</code>.
     */
    public String getMigration() {
        return (String) get(1);
    }

    /**
     * Setter for <code>applet.migrations.batch</code>.
     */
    public void setBatch(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>applet.migrations.batch</code>.
     */
    public Integer getBatch() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<UInteger, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<UInteger, String, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<UInteger> field1() {
        return Migrations.MIGRATIONS.ID;
    }

    @Override
    public Field<String> field2() {
        return Migrations.MIGRATIONS.MIGRATION;
    }

    @Override
    public Field<Integer> field3() {
        return Migrations.MIGRATIONS.BATCH;
    }

    @Override
    public UInteger component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getMigration();
    }

    @Override
    public Integer component3() {
        return getBatch();
    }

    @Override
    public UInteger value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getMigration();
    }

    @Override
    public Integer value3() {
        return getBatch();
    }

    @Override
    public MigrationsRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    @Override
    public MigrationsRecord value2(String value) {
        setMigration(value);
        return this;
    }

    @Override
    public MigrationsRecord value3(Integer value) {
        setBatch(value);
        return this;
    }

    @Override
    public MigrationsRecord values(UInteger value1, String value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MigrationsRecord
     */
    public MigrationsRecord() {
        super(Migrations.MIGRATIONS);
    }

    /**
     * Create a detached, initialised MigrationsRecord
     */
    public MigrationsRecord(UInteger id, String migration, Integer batch) {
        super(Migrations.MIGRATIONS);

        setId(id);
        setMigration(migration);
        setBatch(batch);
    }
}
