/*
 * This file is generated by jOOQ.
 */
package com.opac.scms.tables.records;


import com.opac.scms.tables.NotificationDeviceUsers;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NotificationDeviceUsersRecord extends UpdatableRecordImpl<NotificationDeviceUsersRecord> implements Record6<Integer, Integer, Integer, Byte, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>applet.notification_device_users.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>applet.notification_device_users.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>applet.notification_device_users.notification_id</code>.
     */
    public void setNotificationId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>applet.notification_device_users.notification_id</code>.
     */
    public Integer getNotificationId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>applet.notification_device_users.device_user_id</code>.
     */
    public void setDeviceUserId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>applet.notification_device_users.device_user_id</code>.
     */
    public Integer getDeviceUserId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>applet.notification_device_users.readed</code>.
     */
    public void setReaded(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>applet.notification_device_users.readed</code>.
     */
    public Byte getReaded() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>applet.notification_device_users.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>applet.notification_device_users.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>applet.notification_device_users.modified</code>.
     */
    public void setModified(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>applet.notification_device_users.modified</code>.
     */
    public LocalDateTime getModified() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, Integer, Integer, Byte, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, Integer, Integer, Byte, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return NotificationDeviceUsers.NOTIFICATION_DEVICE_USERS.ID;
    }

    @Override
    public Field<Integer> field2() {
        return NotificationDeviceUsers.NOTIFICATION_DEVICE_USERS.NOTIFICATION_ID;
    }

    @Override
    public Field<Integer> field3() {
        return NotificationDeviceUsers.NOTIFICATION_DEVICE_USERS.DEVICE_USER_ID;
    }

    @Override
    public Field<Byte> field4() {
        return NotificationDeviceUsers.NOTIFICATION_DEVICE_USERS.READED;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return NotificationDeviceUsers.NOTIFICATION_DEVICE_USERS.CREATED;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return NotificationDeviceUsers.NOTIFICATION_DEVICE_USERS.MODIFIED;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getNotificationId();
    }

    @Override
    public Integer component3() {
        return getDeviceUserId();
    }

    @Override
    public Byte component4() {
        return getReaded();
    }

    @Override
    public LocalDateTime component5() {
        return getCreated();
    }

    @Override
    public LocalDateTime component6() {
        return getModified();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getNotificationId();
    }

    @Override
    public Integer value3() {
        return getDeviceUserId();
    }

    @Override
    public Byte value4() {
        return getReaded();
    }

    @Override
    public LocalDateTime value5() {
        return getCreated();
    }

    @Override
    public LocalDateTime value6() {
        return getModified();
    }

    @Override
    public NotificationDeviceUsersRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public NotificationDeviceUsersRecord value2(Integer value) {
        setNotificationId(value);
        return this;
    }

    @Override
    public NotificationDeviceUsersRecord value3(Integer value) {
        setDeviceUserId(value);
        return this;
    }

    @Override
    public NotificationDeviceUsersRecord value4(Byte value) {
        setReaded(value);
        return this;
    }

    @Override
    public NotificationDeviceUsersRecord value5(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public NotificationDeviceUsersRecord value6(LocalDateTime value) {
        setModified(value);
        return this;
    }

    @Override
    public NotificationDeviceUsersRecord values(Integer value1, Integer value2, Integer value3, Byte value4, LocalDateTime value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NotificationDeviceUsersRecord
     */
    public NotificationDeviceUsersRecord() {
        super(NotificationDeviceUsers.NOTIFICATION_DEVICE_USERS);
    }

    /**
     * Create a detached, initialised NotificationDeviceUsersRecord
     */
    public NotificationDeviceUsersRecord(Integer id, Integer notificationId, Integer deviceUserId, Byte readed, LocalDateTime created, LocalDateTime modified) {
        super(NotificationDeviceUsers.NOTIFICATION_DEVICE_USERS);

        setId(id);
        setNotificationId(notificationId);
        setDeviceUserId(deviceUserId);
        setReaded(readed);
        setCreated(created);
        setModified(modified);
    }
}
