/*
 * This file is generated by jOOQ.
 */
package com.opac.scms.tables.records;


import com.opac.scms.tables.Notifications;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NotificationsRecord extends UpdatableRecordImpl<NotificationsRecord> implements Record8<Integer, Integer, Integer, Integer, Byte, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>applet.notifications.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>applet.notifications.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>applet.notifications.advert_id</code>.
     */
    public void setAdvertId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>applet.notifications.advert_id</code>.
     */
    public Integer getAdvertId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>applet.notifications.chat_id</code>.
     */
    public void setChatId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>applet.notifications.chat_id</code>.
     */
    public Integer getChatId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>applet.notifications.user_id</code>. usuario q provoca la notificacion
     */
    public void setUserId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>applet.notifications.user_id</code>. usuario q provoca la notificacion
     */
    public Integer getUserId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>applet.notifications.type</code>.
     */
    public void setType(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>applet.notifications.type</code>.
     */
    public Byte getType() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>applet.notifications.message</code>.
     */
    public void setMessage(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>applet.notifications.message</code>.
     */
    public String getMessage() {
        return (String) get(5);
    }

    /**
     * Setter for <code>applet.notifications.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>applet.notifications.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>applet.notifications.modified</code>.
     */
    public void setModified(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>applet.notifications.modified</code>.
     */
    public LocalDateTime getModified() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, Integer, Integer, Integer, Byte, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Integer, Integer, Integer, Integer, Byte, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Notifications.NOTIFICATIONS.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Notifications.NOTIFICATIONS.ADVERT_ID;
    }

    @Override
    public Field<Integer> field3() {
        return Notifications.NOTIFICATIONS.CHAT_ID;
    }

    @Override
    public Field<Integer> field4() {
        return Notifications.NOTIFICATIONS.USER_ID;
    }

    @Override
    public Field<Byte> field5() {
        return Notifications.NOTIFICATIONS.TYPE;
    }

    @Override
    public Field<String> field6() {
        return Notifications.NOTIFICATIONS.MESSAGE;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return Notifications.NOTIFICATIONS.CREATED;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return Notifications.NOTIFICATIONS.MODIFIED;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getAdvertId();
    }

    @Override
    public Integer component3() {
        return getChatId();
    }

    @Override
    public Integer component4() {
        return getUserId();
    }

    @Override
    public Byte component5() {
        return getType();
    }

    @Override
    public String component6() {
        return getMessage();
    }

    @Override
    public LocalDateTime component7() {
        return getCreated();
    }

    @Override
    public LocalDateTime component8() {
        return getModified();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getAdvertId();
    }

    @Override
    public Integer value3() {
        return getChatId();
    }

    @Override
    public Integer value4() {
        return getUserId();
    }

    @Override
    public Byte value5() {
        return getType();
    }

    @Override
    public String value6() {
        return getMessage();
    }

    @Override
    public LocalDateTime value7() {
        return getCreated();
    }

    @Override
    public LocalDateTime value8() {
        return getModified();
    }

    @Override
    public NotificationsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public NotificationsRecord value2(Integer value) {
        setAdvertId(value);
        return this;
    }

    @Override
    public NotificationsRecord value3(Integer value) {
        setChatId(value);
        return this;
    }

    @Override
    public NotificationsRecord value4(Integer value) {
        setUserId(value);
        return this;
    }

    @Override
    public NotificationsRecord value5(Byte value) {
        setType(value);
        return this;
    }

    @Override
    public NotificationsRecord value6(String value) {
        setMessage(value);
        return this;
    }

    @Override
    public NotificationsRecord value7(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public NotificationsRecord value8(LocalDateTime value) {
        setModified(value);
        return this;
    }

    @Override
    public NotificationsRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Byte value5, String value6, LocalDateTime value7, LocalDateTime value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NotificationsRecord
     */
    public NotificationsRecord() {
        super(Notifications.NOTIFICATIONS);
    }

    /**
     * Create a detached, initialised NotificationsRecord
     */
    public NotificationsRecord(Integer id, Integer advertId, Integer chatId, Integer userId, Byte type, String message, LocalDateTime created, LocalDateTime modified) {
        super(Notifications.NOTIFICATIONS);

        setId(id);
        setAdvertId(advertId);
        setChatId(chatId);
        setUserId(userId);
        setType(type);
        setMessage(message);
        setCreated(created);
        setModified(modified);
    }
}
