/*
 * This file is generated by jOOQ.
 */
package com.opac.scms.tables.records;


import com.opac.scms.tables.PasswordResets;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PasswordResetsRecord extends TableRecordImpl<PasswordResetsRecord> implements Record3<String, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>applet.password_resets.email</code>.
     */
    public void setEmail(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>applet.password_resets.email</code>.
     */
    public String getEmail() {
        return (String) get(0);
    }

    /**
     * Setter for <code>applet.password_resets.token</code>.
     */
    public void setToken(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>applet.password_resets.token</code>.
     */
    public String getToken() {
        return (String) get(1);
    }

    /**
     * Setter for <code>applet.password_resets.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>applet.password_resets.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, String, LocalDateTime> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<String, String, LocalDateTime> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return PasswordResets.PASSWORD_RESETS.EMAIL;
    }

    @Override
    public Field<String> field2() {
        return PasswordResets.PASSWORD_RESETS.TOKEN;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return PasswordResets.PASSWORD_RESETS.CREATED_AT;
    }

    @Override
    public String component1() {
        return getEmail();
    }

    @Override
    public String component2() {
        return getToken();
    }

    @Override
    public LocalDateTime component3() {
        return getCreatedAt();
    }

    @Override
    public String value1() {
        return getEmail();
    }

    @Override
    public String value2() {
        return getToken();
    }

    @Override
    public LocalDateTime value3() {
        return getCreatedAt();
    }

    @Override
    public PasswordResetsRecord value1(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public PasswordResetsRecord value2(String value) {
        setToken(value);
        return this;
    }

    @Override
    public PasswordResetsRecord value3(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public PasswordResetsRecord values(String value1, String value2, LocalDateTime value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PasswordResetsRecord
     */
    public PasswordResetsRecord() {
        super(PasswordResets.PASSWORD_RESETS);
    }

    /**
     * Create a detached, initialised PasswordResetsRecord
     */
    public PasswordResetsRecord(String email, String token, LocalDateTime createdAt) {
        super(PasswordResets.PASSWORD_RESETS);

        setEmail(email);
        setToken(token);
        setCreatedAt(createdAt);
    }
}
