/*
 * This file is generated by jOOQ.
 */
package com.opac.scms.tables.records;


import com.opac.scms.tables.Settings;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SettingsRecord extends UpdatableRecordImpl<SettingsRecord> implements Record9<Integer, BigDecimal, Short, String, BigDecimal, String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>applet.settings.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>applet.settings.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>applet.settings.radius</code>.
     */
    public void setRadius(BigDecimal value) {
        set(1, value);
    }

    /**
     * Getter for <code>applet.settings.radius</code>.
     */
    public BigDecimal getRadius() {
        return (BigDecimal) get(1);
    }

    /**
     * Setter for <code>applet.settings.adverts_per_page</code>.
     */
    public void setAdvertsPerPage(Short value) {
        set(2, value);
    }

    /**
     * Getter for <code>applet.settings.adverts_per_page</code>.
     */
    public Short getAdvertsPerPage() {
        return (Short) get(2);
    }

    /**
     * Setter for <code>applet.settings.contact_email</code>.
     */
    public void setContactEmail(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>applet.settings.contact_email</code>.
     */
    public String getContactEmail() {
        return (String) get(3);
    }

    /**
     * Setter for <code>applet.settings.payment_percent</code>.
     */
    public void setPaymentPercent(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>applet.settings.payment_percent</code>.
     */
    public BigDecimal getPaymentPercent() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>applet.settings.mangopay_key</code>.
     */
    public void setMangopayKey(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>applet.settings.mangopay_key</code>.
     */
    public String getMangopayKey() {
        return (String) get(5);
    }

    /**
     * Setter for <code>applet.settings.mangopay_secret</code>.
     */
    public void setMangopaySecret(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>applet.settings.mangopay_secret</code>.
     */
    public String getMangopaySecret() {
        return (String) get(6);
    }

    /**
     * Setter for <code>applet.settings.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>applet.settings.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>applet.settings.modified</code>.
     */
    public void setModified(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>applet.settings.modified</code>.
     */
    public LocalDateTime getModified() {
        return (LocalDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Integer, BigDecimal, Short, String, BigDecimal, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Integer, BigDecimal, Short, String, BigDecimal, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Settings.SETTINGS.ID;
    }

    @Override
    public Field<BigDecimal> field2() {
        return Settings.SETTINGS.RADIUS;
    }

    @Override
    public Field<Short> field3() {
        return Settings.SETTINGS.ADVERTS_PER_PAGE;
    }

    @Override
    public Field<String> field4() {
        return Settings.SETTINGS.CONTACT_EMAIL;
    }

    @Override
    public Field<BigDecimal> field5() {
        return Settings.SETTINGS.PAYMENT_PERCENT;
    }

    @Override
    public Field<String> field6() {
        return Settings.SETTINGS.MANGOPAY_KEY;
    }

    @Override
    public Field<String> field7() {
        return Settings.SETTINGS.MANGOPAY_SECRET;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return Settings.SETTINGS.CREATED;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return Settings.SETTINGS.MODIFIED;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public BigDecimal component2() {
        return getRadius();
    }

    @Override
    public Short component3() {
        return getAdvertsPerPage();
    }

    @Override
    public String component4() {
        return getContactEmail();
    }

    @Override
    public BigDecimal component5() {
        return getPaymentPercent();
    }

    @Override
    public String component6() {
        return getMangopayKey();
    }

    @Override
    public String component7() {
        return getMangopaySecret();
    }

    @Override
    public LocalDateTime component8() {
        return getCreated();
    }

    @Override
    public LocalDateTime component9() {
        return getModified();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public BigDecimal value2() {
        return getRadius();
    }

    @Override
    public Short value3() {
        return getAdvertsPerPage();
    }

    @Override
    public String value4() {
        return getContactEmail();
    }

    @Override
    public BigDecimal value5() {
        return getPaymentPercent();
    }

    @Override
    public String value6() {
        return getMangopayKey();
    }

    @Override
    public String value7() {
        return getMangopaySecret();
    }

    @Override
    public LocalDateTime value8() {
        return getCreated();
    }

    @Override
    public LocalDateTime value9() {
        return getModified();
    }

    @Override
    public SettingsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public SettingsRecord value2(BigDecimal value) {
        setRadius(value);
        return this;
    }

    @Override
    public SettingsRecord value3(Short value) {
        setAdvertsPerPage(value);
        return this;
    }

    @Override
    public SettingsRecord value4(String value) {
        setContactEmail(value);
        return this;
    }

    @Override
    public SettingsRecord value5(BigDecimal value) {
        setPaymentPercent(value);
        return this;
    }

    @Override
    public SettingsRecord value6(String value) {
        setMangopayKey(value);
        return this;
    }

    @Override
    public SettingsRecord value7(String value) {
        setMangopaySecret(value);
        return this;
    }

    @Override
    public SettingsRecord value8(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public SettingsRecord value9(LocalDateTime value) {
        setModified(value);
        return this;
    }

    @Override
    public SettingsRecord values(Integer value1, BigDecimal value2, Short value3, String value4, BigDecimal value5, String value6, String value7, LocalDateTime value8, LocalDateTime value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SettingsRecord
     */
    public SettingsRecord() {
        super(Settings.SETTINGS);
    }

    /**
     * Create a detached, initialised SettingsRecord
     */
    public SettingsRecord(Integer id, BigDecimal radius, Short advertsPerPage, String contactEmail, BigDecimal paymentPercent, String mangopayKey, String mangopaySecret, LocalDateTime created, LocalDateTime modified) {
        super(Settings.SETTINGS);

        setId(id);
        setRadius(radius);
        setAdvertsPerPage(advertsPerPage);
        setContactEmail(contactEmail);
        setPaymentPercent(paymentPercent);
        setMangopayKey(mangopayKey);
        setMangopaySecret(mangopaySecret);
        setCreated(created);
        setModified(modified);
    }
}
