/*
 * This file is generated by jOOQ.
 */
package com.opac.scms.tables.records;


import com.opac.scms.tables.UsersCopy;

import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersCopyRecord extends TableRecordImpl<UsersCopyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>applet.users_copy.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>applet.users_copy.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>applet.users_copy.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>applet.users_copy.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>applet.users_copy.phone</code>.
     */
    public void setPhone(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>applet.users_copy.phone</code>.
     */
    public String getPhone() {
        return (String) get(2);
    }

    /**
     * Setter for <code>applet.users_copy.last_name</code>.
     */
    public void setLastName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>applet.users_copy.last_name</code>.
     */
    public String getLastName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>applet.users_copy.email</code>.
     */
    public void setEmail(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>applet.users_copy.email</code>.
     */
    public String getEmail() {
        return (String) get(4);
    }

    /**
     * Setter for <code>applet.users_copy.username</code>.
     */
    public void setUsername(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>applet.users_copy.username</code>.
     */
    public String getUsername() {
        return (String) get(5);
    }

    /**
     * Setter for <code>applet.users_copy.password</code>.
     */
    public void setPassword(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>applet.users_copy.password</code>.
     */
    public String getPassword() {
        return (String) get(6);
    }

    /**
     * Setter for <code>applet.users_copy.active</code>.
     */
    public void setActive(Byte value) {
        set(7, value);
    }

    /**
     * Getter for <code>applet.users_copy.active</code>.
     */
    public Byte getActive() {
        return (Byte) get(7);
    }

    /**
     * Setter for <code>applet.users_copy.facebook_id</code>.
     */
    public void setFacebookId(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>applet.users_copy.facebook_id</code>.
     */
    public String getFacebookId() {
        return (String) get(8);
    }

    /**
     * Setter for <code>applet.users_copy.google_id</code>.
     */
    public void setGoogleId(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>applet.users_copy.google_id</code>.
     */
    public String getGoogleId() {
        return (String) get(9);
    }

    /**
     * Setter for <code>applet.users_copy.twitter_id</code>.
     */
    public void setTwitterId(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>applet.users_copy.twitter_id</code>.
     */
    public String getTwitterId() {
        return (String) get(10);
    }

    /**
     * Setter for <code>applet.users_copy.last_connection</code>.
     */
    public void setLastConnection(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>applet.users_copy.last_connection</code>.
     */
    public LocalDateTime getLastConnection() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>applet.users_copy.mangopay_id</code>.
     */
    public void setMangopayId(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>applet.users_copy.mangopay_id</code>.
     */
    public String getMangopayId() {
        return (String) get(12);
    }

    /**
     * Setter for <code>applet.users_copy.wallet_id</code>.
     */
    public void setWalletId(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>applet.users_copy.wallet_id</code>.
     */
    public String getWalletId() {
        return (String) get(13);
    }

    /**
     * Setter for <code>applet.users_copy.card_id</code>.
     */
    public void setCardId(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>applet.users_copy.card_id</code>.
     */
    public String getCardId() {
        return (String) get(14);
    }

    /**
     * Setter for <code>applet.users_copy.registration_data</code>.
     */
    public void setRegistrationData(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>applet.users_copy.registration_data</code>.
     */
    public String getRegistrationData() {
        return (String) get(15);
    }

    /**
     * Setter for <code>applet.users_copy.access_key</code>.
     */
    public void setAccessKey(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>applet.users_copy.access_key</code>.
     */
    public String getAccessKey() {
        return (String) get(16);
    }

    /**
     * Setter for <code>applet.users_copy.card_register_data_id</code>.
     */
    public void setCardRegisterDataId(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>applet.users_copy.card_register_data_id</code>.
     */
    public String getCardRegisterDataId() {
        return (String) get(17);
    }

    /**
     * Setter for <code>applet.users_copy.card_registration_url</code>.
     */
    public void setCardRegistrationUrl(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>applet.users_copy.card_registration_url</code>.
     */
    public String getCardRegistrationUrl() {
        return (String) get(18);
    }

    /**
     * Setter for <code>applet.users_copy.card_number</code>.
     */
    public void setCardNumber(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>applet.users_copy.card_number</code>.
     */
    public String getCardNumber() {
        return (String) get(19);
    }

    /**
     * Setter for <code>applet.users_copy.card_expiration_date</code>.
     */
    public void setCardExpirationDate(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>applet.users_copy.card_expiration_date</code>.
     */
    public String getCardExpirationDate() {
        return (String) get(20);
    }

    /**
     * Setter for <code>applet.users_copy.bank_account</code>.
     */
    public void setBankAccount(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>applet.users_copy.bank_account</code>.
     */
    public String getBankAccount() {
        return (String) get(21);
    }

    /**
     * Setter for <code>applet.users_copy.bank_account_id</code>.
     */
    public void setBankAccountId(Integer value) {
        set(22, value);
    }

    /**
     * Getter for <code>applet.users_copy.bank_account_id</code>.
     */
    public Integer getBankAccountId() {
        return (Integer) get(22);
    }

    /**
     * Setter for <code>applet.users_copy.birthday</code>.
     */
    public void setBirthday(LocalDate value) {
        set(23, value);
    }

    /**
     * Getter for <code>applet.users_copy.birthday</code>.
     */
    public LocalDate getBirthday() {
        return (LocalDate) get(23);
    }

    /**
     * Setter for <code>applet.users_copy.nationality</code>.
     */
    public void setNationality(String value) {
        set(24, value);
    }

    /**
     * Getter for <code>applet.users_copy.nationality</code>.
     */
    public String getNationality() {
        return (String) get(24);
    }

    /**
     * Setter for <code>applet.users_copy.country_of_residence</code>.
     */
    public void setCountryOfResidence(String value) {
        set(25, value);
    }

    /**
     * Getter for <code>applet.users_copy.country_of_residence</code>.
     */
    public String getCountryOfResidence() {
        return (String) get(25);
    }

    /**
     * Setter for <code>applet.users_copy.nif</code>.
     */
    public void setNif(String value) {
        set(26, value);
    }

    /**
     * Getter for <code>applet.users_copy.nif</code>.
     */
    public String getNif() {
        return (String) get(26);
    }

    /**
     * Setter for <code>applet.users_copy.address</code>.
     */
    public void setAddress(String value) {
        set(27, value);
    }

    /**
     * Getter for <code>applet.users_copy.address</code>.
     */
    public String getAddress() {
        return (String) get(27);
    }

    /**
     * Setter for <code>applet.users_copy.city</code>.
     */
    public void setCity(String value) {
        set(28, value);
    }

    /**
     * Getter for <code>applet.users_copy.city</code>.
     */
    public String getCity() {
        return (String) get(28);
    }

    /**
     * Setter for <code>applet.users_copy.postal_code</code>.
     */
    public void setPostalCode(String value) {
        set(29, value);
    }

    /**
     * Getter for <code>applet.users_copy.postal_code</code>.
     */
    public String getPostalCode() {
        return (String) get(29);
    }

    /**
     * Setter for <code>applet.users_copy.image_uri</code>.
     */
    public void setImageUri(String value) {
        set(30, value);
    }

    /**
     * Getter for <code>applet.users_copy.image_uri</code>.
     */
    public String getImageUri() {
        return (String) get(30);
    }

    /**
     * Setter for <code>applet.users_copy.header_uri</code>.
     */
    public void setHeaderUri(String value) {
        set(31, value);
    }

    /**
     * Getter for <code>applet.users_copy.header_uri</code>.
     */
    public String getHeaderUri() {
        return (String) get(31);
    }

    /**
     * Setter for <code>applet.users_copy.advert_published_count</code>.
     */
    public void setAdvertPublishedCount(Integer value) {
        set(32, value);
    }

    /**
     * Getter for <code>applet.users_copy.advert_published_count</code>.
     */
    public Integer getAdvertPublishedCount() {
        return (Integer) get(32);
    }

    /**
     * Setter for <code>applet.users_copy.advert_count</code>.
     */
    public void setAdvertCount(Integer value) {
        set(33, value);
    }

    /**
     * Getter for <code>applet.users_copy.advert_count</code>.
     */
    public Integer getAdvertCount() {
        return (Integer) get(33);
    }

    /**
     * Setter for <code>applet.users_copy.end_date</code>.
     */
    public void setEndDate(LocalDate value) {
        set(34, value);
    }

    /**
     * Getter for <code>applet.users_copy.end_date</code>.
     */
    public LocalDate getEndDate() {
        return (LocalDate) get(34);
    }

    /**
     * Setter for <code>applet.users_copy.notification_messages</code>.
     */
    public void setNotificationMessages(Byte value) {
        set(35, value);
    }

    /**
     * Getter for <code>applet.users_copy.notification_messages</code>.
     */
    public Byte getNotificationMessages() {
        return (Byte) get(35);
    }

    /**
     * Setter for <code>applet.users_copy.notification_adverts</code>.
     */
    public void setNotificationAdverts(Byte value) {
        set(36, value);
    }

    /**
     * Getter for <code>applet.users_copy.notification_adverts</code>.
     */
    public Byte getNotificationAdverts() {
        return (Byte) get(36);
    }

    /**
     * Setter for <code>applet.users_copy.alert_radius</code>.
     */
    public void setAlertRadius(Integer value) {
        set(37, value);
    }

    /**
     * Getter for <code>applet.users_copy.alert_radius</code>.
     */
    public Integer getAlertRadius() {
        return (Integer) get(37);
    }

    /**
     * Setter for <code>applet.users_copy.language</code>.
     */
    public void setLanguage(String value) {
        set(38, value);
    }

    /**
     * Getter for <code>applet.users_copy.language</code>.
     */
    public String getLanguage() {
        return (String) get(38);
    }

    /**
     * Setter for <code>applet.users_copy.stripe_account_id</code>.
     */
    public void setStripeAccountId(String value) {
        set(39, value);
    }

    /**
     * Getter for <code>applet.users_copy.stripe_account_id</code>.
     */
    public String getStripeAccountId() {
        return (String) get(39);
    }

    /**
     * Setter for <code>applet.users_copy.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(40, value);
    }

    /**
     * Getter for <code>applet.users_copy.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(40);
    }

    /**
     * Setter for <code>applet.users_copy.modified</code>.
     */
    public void setModified(LocalDateTime value) {
        set(41, value);
    }

    /**
     * Getter for <code>applet.users_copy.modified</code>.
     */
    public LocalDateTime getModified() {
        return (LocalDateTime) get(41);
    }

    /**
     * Setter for <code>applet.users_copy.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(42, value);
    }

    /**
     * Getter for <code>applet.users_copy.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(42);
    }

    /**
     * Setter for <code>applet.users_copy.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(43, value);
    }

    /**
     * Getter for <code>applet.users_copy.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(43);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersCopyRecord
     */
    public UsersCopyRecord() {
        super(UsersCopy.USERS_COPY);
    }

    /**
     * Create a detached, initialised UsersCopyRecord
     */
    public UsersCopyRecord(Integer id, String name, String phone, String lastName, String email, String username, String password, Byte active, String facebookId, String googleId, String twitterId, LocalDateTime lastConnection, String mangopayId, String walletId, String cardId, String registrationData, String accessKey, String cardRegisterDataId, String cardRegistrationUrl, String cardNumber, String cardExpirationDate, String bankAccount, Integer bankAccountId, LocalDate birthday, String nationality, String countryOfResidence, String nif, String address, String city, String postalCode, String imageUri, String headerUri, Integer advertPublishedCount, Integer advertCount, LocalDate endDate, Byte notificationMessages, Byte notificationAdverts, Integer alertRadius, String language, String stripeAccountId, LocalDateTime created, LocalDateTime modified, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(UsersCopy.USERS_COPY);

        setId(id);
        setName(name);
        setPhone(phone);
        setLastName(lastName);
        setEmail(email);
        setUsername(username);
        setPassword(password);
        setActive(active);
        setFacebookId(facebookId);
        setGoogleId(googleId);
        setTwitterId(twitterId);
        setLastConnection(lastConnection);
        setMangopayId(mangopayId);
        setWalletId(walletId);
        setCardId(cardId);
        setRegistrationData(registrationData);
        setAccessKey(accessKey);
        setCardRegisterDataId(cardRegisterDataId);
        setCardRegistrationUrl(cardRegistrationUrl);
        setCardNumber(cardNumber);
        setCardExpirationDate(cardExpirationDate);
        setBankAccount(bankAccount);
        setBankAccountId(bankAccountId);
        setBirthday(birthday);
        setNationality(nationality);
        setCountryOfResidence(countryOfResidence);
        setNif(nif);
        setAddress(address);
        setCity(city);
        setPostalCode(postalCode);
        setImageUri(imageUri);
        setHeaderUri(headerUri);
        setAdvertPublishedCount(advertPublishedCount);
        setAdvertCount(advertCount);
        setEndDate(endDate);
        setNotificationMessages(notificationMessages);
        setNotificationAdverts(notificationAdverts);
        setAlertRadius(alertRadius);
        setLanguage(language);
        setStripeAccountId(stripeAccountId);
        setCreated(created);
        setModified(modified);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
    }
}
