/*
 * This file is generated by jOOQ.
 */
package com.opac.scms.tables.records;


import com.opac.scms.tables.VerifyAccount;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VerifyAccountRecord extends UpdatableRecordImpl<VerifyAccountRecord> implements Record5<Long, LocalDateTime, LocalDateTime, String, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>applet.verify_account.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>applet.verify_account.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>applet.verify_account.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>applet.verify_account.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>applet.verify_account.expired_data_token</code>.
     */
    public void setExpiredDataToken(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>applet.verify_account.expired_data_token</code>.
     */
    public LocalDateTime getExpiredDataToken() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>applet.verify_account.token</code>.
     */
    public void setToken(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>applet.verify_account.token</code>.
     */
    public String getToken() {
        return (String) get(3);
    }

    /**
     * Setter for <code>applet.verify_account.account_id</code>.
     */
    public void setAccountId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>applet.verify_account.account_id</code>.
     */
    public Long getAccountId() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, LocalDateTime, LocalDateTime, String, Long> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, LocalDateTime, LocalDateTime, String, Long> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return VerifyAccount.VERIFY_ACCOUNT.ID;
    }

    @Override
    public Field<LocalDateTime> field2() {
        return VerifyAccount.VERIFY_ACCOUNT.CREATED_DATE;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return VerifyAccount.VERIFY_ACCOUNT.EXPIRED_DATA_TOKEN;
    }

    @Override
    public Field<String> field4() {
        return VerifyAccount.VERIFY_ACCOUNT.TOKEN;
    }

    @Override
    public Field<Long> field5() {
        return VerifyAccount.VERIFY_ACCOUNT.ACCOUNT_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public LocalDateTime component2() {
        return getCreatedDate();
    }

    @Override
    public LocalDateTime component3() {
        return getExpiredDataToken();
    }

    @Override
    public String component4() {
        return getToken();
    }

    @Override
    public Long component5() {
        return getAccountId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public LocalDateTime value2() {
        return getCreatedDate();
    }

    @Override
    public LocalDateTime value3() {
        return getExpiredDataToken();
    }

    @Override
    public String value4() {
        return getToken();
    }

    @Override
    public Long value5() {
        return getAccountId();
    }

    @Override
    public VerifyAccountRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public VerifyAccountRecord value2(LocalDateTime value) {
        setCreatedDate(value);
        return this;
    }

    @Override
    public VerifyAccountRecord value3(LocalDateTime value) {
        setExpiredDataToken(value);
        return this;
    }

    @Override
    public VerifyAccountRecord value4(String value) {
        setToken(value);
        return this;
    }

    @Override
    public VerifyAccountRecord value5(Long value) {
        setAccountId(value);
        return this;
    }

    @Override
    public VerifyAccountRecord values(Long value1, LocalDateTime value2, LocalDateTime value3, String value4, Long value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VerifyAccountRecord
     */
    public VerifyAccountRecord() {
        super(VerifyAccount.VERIFY_ACCOUNT);
    }

    /**
     * Create a detached, initialised VerifyAccountRecord
     */
    public VerifyAccountRecord(Long id, LocalDateTime createdDate, LocalDateTime expiredDataToken, String token, Long accountId) {
        super(VerifyAccount.VERIFY_ACCOUNT);

        setId(id);
        setCreatedDate(createdDate);
        setExpiredDataToken(expiredDataToken);
        setToken(token);
        setAccountId(accountId);
    }
}
